<?php

/**
 * BusinessPlan filter form base class.
 *
 * @package    rdbeportal
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseBusinessPlanFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'investment_id'                   => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('InvestmentApplication'), 'add_empty' => true)),
      'land_year1'                      => new sfWidgetFormFilterInput(),
      'land_year2'                      => new sfWidgetFormFilterInput(),
      'land_year3'                      => new sfWidgetFormFilterInput(),
      'land_year4'                      => new sfWidgetFormFilterInput(),
      'land_year5'                      => new sfWidgetFormFilterInput(),
      'construction_year1'              => new sfWidgetFormFilterInput(),
      'construction_year2'              => new sfWidgetFormFilterInput(),
      'construction_year3'              => new sfWidgetFormFilterInput(),
      'construction_year4'              => new sfWidgetFormFilterInput(),
      'construction_year5'              => new sfWidgetFormFilterInput(),
      'machinery_year1'                 => new sfWidgetFormFilterInput(),
      'machinery_year2'                 => new sfWidgetFormFilterInput(),
      'machinery_year3'                 => new sfWidgetFormFilterInput(),
      'machinery_year4'                 => new sfWidgetFormFilterInput(),
      'machinery_year5'                 => new sfWidgetFormFilterInput(),
      'furniture_year1'                 => new sfWidgetFormFilterInput(),
      'furniture_year2'                 => new sfWidgetFormFilterInput(),
      'furniture_year3'                 => new sfWidgetFormFilterInput(),
      'furniture_year4'                 => new sfWidgetFormFilterInput(),
      'furniture_year5'                 => new sfWidgetFormFilterInput(),
      'other_assets1'                   => new sfWidgetFormFilterInput(),
      'other_assets2'                   => new sfWidgetFormFilterInput(),
      'other_assets3'                   => new sfWidgetFormFilterInput(),
      'other_assets4'                   => new sfWidgetFormFilterInput(),
      'other_assets5'                   => new sfWidgetFormFilterInput(),
      'studies_year1'                   => new sfWidgetFormFilterInput(),
      'studies_year2'                   => new sfWidgetFormFilterInput(),
      'studies_year3'                   => new sfWidgetFormFilterInput(),
      'studies_year4'                   => new sfWidgetFormFilterInput(),
      'studies_year5'                   => new sfWidgetFormFilterInput(),
      'travel_expenses1'                => new sfWidgetFormFilterInput(),
      'travel_expenses2'                => new sfWidgetFormFilterInput(),
      'travel_expenses3'                => new sfWidgetFormFilterInput(),
      'travel_expenses4'                => new sfWidgetFormFilterInput(),
      'travel_expenses5'                => new sfWidgetFormFilterInput(),
      'starting_capital1'               => new sfWidgetFormFilterInput(),
      'starting_capital2'               => new sfWidgetFormFilterInput(),
      'starting_capital3'               => new sfWidgetFormFilterInput(),
      'starting_capital4'               => new sfWidgetFormFilterInput(),
      'starting_capital5'               => new sfWidgetFormFilterInput(),
      'licensing_expenses1'             => new sfWidgetFormFilterInput(),
      'licensing_expenses2'             => new sfWidgetFormFilterInput(),
      'licensing_expenses3'             => new sfWidgetFormFilterInput(),
      'licensing_expenses4'             => new sfWidgetFormFilterInput(),
      'licensing_expenses5'             => new sfWidgetFormFilterInput(),
      'rental_fees1'                    => new sfWidgetFormFilterInput(),
      'rental_fees2'                    => new sfWidgetFormFilterInput(),
      'rental_fees3'                    => new sfWidgetFormFilterInput(),
      'rental_fees4'                    => new sfWidgetFormFilterInput(),
      'rental_fees5'                    => new sfWidgetFormFilterInput(),
      'other_expeses1'                  => new sfWidgetFormFilterInput(),
      'other_expeses2'                  => new sfWidgetFormFilterInput(),
      'other_expeses3'                  => new sfWidgetFormFilterInput(),
      'other_expeses4'                  => new sfWidgetFormFilterInput(),
      'other_expeses5'                  => new sfWidgetFormFilterInput(),
      'equity_local'                    => new sfWidgetFormFilterInput(),
      'equity_foregin'                  => new sfWidgetFormFilterInput(),
      'bank_loan_local'                 => new sfWidgetFormFilterInput(),
      'bank_loan_foreign'               => new sfWidgetFormFilterInput(),
      'mother_company_loan_local'       => new sfWidgetFormFilterInput(),
      'mother_company_loan_foreign'     => new sfWidgetFormFilterInput(),
      'grant_local'                     => new sfWidgetFormFilterInput(),
      'grant_foreign'                   => new sfWidgetFormFilterInput(),
      'top_management_local1'           => new sfWidgetFormFilterInput(),
      'top_management_local2'           => new sfWidgetFormFilterInput(),
      'top_management_local3'           => new sfWidgetFormFilterInput(),
      'top_management_local4'           => new sfWidgetFormFilterInput(),
      'top_management_local5'           => new sfWidgetFormFilterInput(),
      'top_management_foreign1'         => new sfWidgetFormFilterInput(),
      'top_management_foreign2'         => new sfWidgetFormFilterInput(),
      'top_management_foreign3'         => new sfWidgetFormFilterInput(),
      'top_management_foreign4'         => new sfWidgetFormFilterInput(),
      'top_management_foreign5'         => new sfWidgetFormFilterInput(),
      'technical_professional_local1'   => new sfWidgetFormFilterInput(),
      'technical_professional_local2'   => new sfWidgetFormFilterInput(),
      'technical_professional_local3'   => new sfWidgetFormFilterInput(),
      'technical_professional_local4'   => new sfWidgetFormFilterInput(),
      'technical_professional_local5'   => new sfWidgetFormFilterInput(),
      'technical_professional_foreign1' => new sfWidgetFormFilterInput(),
      'technical_professional_foreign2' => new sfWidgetFormFilterInput(),
      'technical_professional_foreign3' => new sfWidgetFormFilterInput(),
      'technical_professional_foreign4' => new sfWidgetFormFilterInput(),
      'technical_professional_foreign5' => new sfWidgetFormFilterInput(),
      'skilled_labour_local1'           => new sfWidgetFormFilterInput(),
      'skilled_labour_local2'           => new sfWidgetFormFilterInput(),
      'skilled_labour_local3'           => new sfWidgetFormFilterInput(),
      'skilled_labour_local4'           => new sfWidgetFormFilterInput(),
      'skilled_labour_local5'           => new sfWidgetFormFilterInput(),
      'skilled_labour_foreign1'         => new sfWidgetFormFilterInput(),
      'skilled_labour_foreign2'         => new sfWidgetFormFilterInput(),
      'skilled_labour_foreign3'         => new sfWidgetFormFilterInput(),
      'skilled_labour_foreign4'         => new sfWidgetFormFilterInput(),
      'skilled_labour_foreign5'         => new sfWidgetFormFilterInput(),
      'other_jobs_local1'               => new sfWidgetFormFilterInput(),
      'other_jobs_local2'               => new sfWidgetFormFilterInput(),
      'other_jobs_local3'               => new sfWidgetFormFilterInput(),
      'other_jobs_local4'               => new sfWidgetFormFilterInput(),
      'other_jobs_local5'               => new sfWidgetFormFilterInput(),
      'other_jobs_foreign1'             => new sfWidgetFormFilterInput(),
      'other_jobs_foreign2'             => new sfWidgetFormFilterInput(),
      'other_jobs_foreign3'             => new sfWidgetFormFilterInput(),
      'other_jobs_foreign4'             => new sfWidgetFormFilterInput(),
      'other_jobs_foreign5'             => new sfWidgetFormFilterInput(),
      'sales_income1'                   => new sfWidgetFormFilterInput(),
      'sales_income2'                   => new sfWidgetFormFilterInput(),
      'sales_income3'                   => new sfWidgetFormFilterInput(),
      'sales_income4'                   => new sfWidgetFormFilterInput(),
      'sales_income5'                   => new sfWidgetFormFilterInput(),
      'total_cost_sales1'               => new sfWidgetFormFilterInput(),
      'total_cost_sales2'               => new sfWidgetFormFilterInput(),
      'total_cost_sales3'               => new sfWidgetFormFilterInput(),
      'total_cost_sales4'               => new sfWidgetFormFilterInput(),
      'total_cost_sales5'               => new sfWidgetFormFilterInput(),
      'gross_profit1'                   => new sfWidgetFormFilterInput(),
      'gross_profit2'                   => new sfWidgetFormFilterInput(),
      'gross_profit3'                   => new sfWidgetFormFilterInput(),
      'gross_profit4'                   => new sfWidgetFormFilterInput(),
      'gross_profit5'                   => new sfWidgetFormFilterInput(),
      'indirect_expenses1'              => new sfWidgetFormFilterInput(),
      'indirect_expenses2'              => new sfWidgetFormFilterInput(),
      'indirect_expenses3'              => new sfWidgetFormFilterInput(),
      'indirect_expenses4'              => new sfWidgetFormFilterInput(),
      'indirect_expenses5'              => new sfWidgetFormFilterInput(),
      'profit_before_tax1'              => new sfWidgetFormFilterInput(),
      'profit_before_tax2'              => new sfWidgetFormFilterInput(),
      'profit_before_tax3'              => new sfWidgetFormFilterInput(),
      'profit_before_tax4'              => new sfWidgetFormFilterInput(),
      'profit_before_tax5'              => new sfWidgetFormFilterInput(),
      'tax_expenses1'                   => new sfWidgetFormFilterInput(),
      'tax_expenses2'                   => new sfWidgetFormFilterInput(),
      'tax_expenses3'                   => new sfWidgetFormFilterInput(),
      'tax_expenses4'                   => new sfWidgetFormFilterInput(),
      'tax_expenses5'                   => new sfWidgetFormFilterInput(),
      'net_profit1'                     => new sfWidgetFormFilterInput(),
      'net_profit2'                     => new sfWidgetFormFilterInput(),
      'net_profit3'                     => new sfWidgetFormFilterInput(),
      'net_profit4'                     => new sfWidgetFormFilterInput(),
      'net_profit5'                     => new sfWidgetFormFilterInput(),
      'project_brief'                   => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'exemption_on_machinery'          => new sfWidgetFormFilterInput(),
      'exemption_raw_materials'         => new sfWidgetFormFilterInput(),
      'land_ownership_document'         => new sfWidgetFormFilterInput(),
      'bill_of_quantiy'                 => new sfWidgetFormFilterInput(),
      'drawings'                        => new sfWidgetFormFilterInput(),
      'construction_permits'            => new sfWidgetFormFilterInput(),
      'investment_allowances'           => new sfWidgetFormFilterInput(),
      'additional_incentives'           => new sfWidgetFormFilterInput(),
      'visa_work_permits'               => new sfWidgetFormFilterInput(),
      'created_at'                      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'updated_at'                      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'created_by'                      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Creator'), 'add_empty' => true)),
      'updated_by'                      => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'investment_id'                   => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('InvestmentApplication'), 'column' => 'id')),
      'land_year1'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'land_year2'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'land_year3'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'land_year4'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'land_year5'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'construction_year1'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'construction_year2'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'construction_year3'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'construction_year4'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'construction_year5'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'machinery_year1'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'machinery_year2'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'machinery_year3'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'machinery_year4'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'machinery_year5'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'furniture_year1'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'furniture_year2'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'furniture_year3'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'furniture_year4'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'furniture_year5'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_assets1'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_assets2'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_assets3'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_assets4'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_assets5'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'studies_year1'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'studies_year2'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'studies_year3'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'studies_year4'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'studies_year5'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'travel_expenses1'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'travel_expenses2'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'travel_expenses3'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'travel_expenses4'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'travel_expenses5'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'starting_capital1'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'starting_capital2'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'starting_capital3'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'starting_capital4'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'starting_capital5'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'licensing_expenses1'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'licensing_expenses2'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'licensing_expenses3'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'licensing_expenses4'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'licensing_expenses5'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rental_fees1'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rental_fees2'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rental_fees3'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rental_fees4'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rental_fees5'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_expeses1'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_expeses2'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_expeses3'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_expeses4'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_expeses5'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'equity_local'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'equity_foregin'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'bank_loan_local'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'bank_loan_foreign'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mother_company_loan_local'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mother_company_loan_foreign'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'grant_local'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'grant_foreign'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_local1'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_local2'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_local3'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_local4'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_local5'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_foreign1'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_foreign2'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_foreign3'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_foreign4'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'top_management_foreign5'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_local1'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_local2'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_local3'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_local4'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_local5'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_foreign1' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_foreign2' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_foreign3' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_foreign4' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'technical_professional_foreign5' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_local1'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_local2'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_local3'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_local4'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_local5'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_foreign1'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_foreign2'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_foreign3'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_foreign4'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'skilled_labour_foreign5'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_local1'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_local2'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_local3'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_local4'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_local5'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_foreign1'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_foreign2'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_foreign3'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_foreign4'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_jobs_foreign5'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'sales_income1'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'sales_income2'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'sales_income3'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'sales_income4'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'sales_income5'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'total_cost_sales1'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'total_cost_sales2'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'total_cost_sales3'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'total_cost_sales4'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'total_cost_sales5'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gross_profit1'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gross_profit2'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gross_profit3'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gross_profit4'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gross_profit5'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'indirect_expenses1'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'indirect_expenses2'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'indirect_expenses3'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'indirect_expenses4'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'indirect_expenses5'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'profit_before_tax1'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'profit_before_tax2'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'profit_before_tax3'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'profit_before_tax4'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'profit_before_tax5'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tax_expenses1'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tax_expenses2'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tax_expenses3'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tax_expenses4'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tax_expenses5'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'net_profit1'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'net_profit2'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'net_profit3'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'net_profit4'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'net_profit5'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'project_brief'                   => new sfValidatorPass(array('required' => false)),
      'exemption_on_machinery'          => new sfValidatorPass(array('required' => false)),
      'exemption_raw_materials'         => new sfValidatorPass(array('required' => false)),
      'land_ownership_document'         => new sfValidatorPass(array('required' => false)),
      'bill_of_quantiy'                 => new sfValidatorPass(array('required' => false)),
      'drawings'                        => new sfValidatorPass(array('required' => false)),
      'construction_permits'            => new sfValidatorPass(array('required' => false)),
      'investment_allowances'           => new sfValidatorPass(array('required' => false)),
      'additional_incentives'           => new sfValidatorPass(array('required' => false)),
      'visa_work_permits'               => new sfValidatorPass(array('required' => false)),
      'created_at'                      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'updated_at'                      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'created_by'                      => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Creator'), 'column' => 'id')),
      'updated_by'                      => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('business_plan_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'BusinessPlan';
  }

  public function getFields()
  {
    return array(
      'id'                              => 'Number',
      'investment_id'                   => 'ForeignKey',
      'land_year1'                      => 'Number',
      'land_year2'                      => 'Number',
      'land_year3'                      => 'Number',
      'land_year4'                      => 'Number',
      'land_year5'                      => 'Number',
      'construction_year1'              => 'Number',
      'construction_year2'              => 'Number',
      'construction_year3'              => 'Number',
      'construction_year4'              => 'Number',
      'construction_year5'              => 'Number',
      'machinery_year1'                 => 'Number',
      'machinery_year2'                 => 'Number',
      'machinery_year3'                 => 'Number',
      'machinery_year4'                 => 'Number',
      'machinery_year5'                 => 'Number',
      'furniture_year1'                 => 'Number',
      'furniture_year2'                 => 'Number',
      'furniture_year3'                 => 'Number',
      'furniture_year4'                 => 'Number',
      'furniture_year5'                 => 'Number',
      'other_assets1'                   => 'Number',
      'other_assets2'                   => 'Number',
      'other_assets3'                   => 'Number',
      'other_assets4'                   => 'Number',
      'other_assets5'                   => 'Number',
      'studies_year1'                   => 'Number',
      'studies_year2'                   => 'Number',
      'studies_year3'                   => 'Number',
      'studies_year4'                   => 'Number',
      'studies_year5'                   => 'Number',
      'travel_expenses1'                => 'Number',
      'travel_expenses2'                => 'Number',
      'travel_expenses3'                => 'Number',
      'travel_expenses4'                => 'Number',
      'travel_expenses5'                => 'Number',
      'starting_capital1'               => 'Number',
      'starting_capital2'               => 'Number',
      'starting_capital3'               => 'Number',
      'starting_capital4'               => 'Number',
      'starting_capital5'               => 'Number',
      'licensing_expenses1'             => 'Number',
      'licensing_expenses2'             => 'Number',
      'licensing_expenses3'             => 'Number',
      'licensing_expenses4'             => 'Number',
      'licensing_expenses5'             => 'Number',
      'rental_fees1'                    => 'Number',
      'rental_fees2'                    => 'Number',
      'rental_fees3'                    => 'Number',
      'rental_fees4'                    => 'Number',
      'rental_fees5'                    => 'Number',
      'other_expeses1'                  => 'Number',
      'other_expeses2'                  => 'Number',
      'other_expeses3'                  => 'Number',
      'other_expeses4'                  => 'Number',
      'other_expeses5'                  => 'Number',
      'equity_local'                    => 'Number',
      'equity_foregin'                  => 'Number',
      'bank_loan_local'                 => 'Number',
      'bank_loan_foreign'               => 'Number',
      'mother_company_loan_local'       => 'Number',
      'mother_company_loan_foreign'     => 'Number',
      'grant_local'                     => 'Number',
      'grant_foreign'                   => 'Number',
      'top_management_local1'           => 'Number',
      'top_management_local2'           => 'Number',
      'top_management_local3'           => 'Number',
      'top_management_local4'           => 'Number',
      'top_management_local5'           => 'Number',
      'top_management_foreign1'         => 'Number',
      'top_management_foreign2'         => 'Number',
      'top_management_foreign3'         => 'Number',
      'top_management_foreign4'         => 'Number',
      'top_management_foreign5'         => 'Number',
      'technical_professional_local1'   => 'Number',
      'technical_professional_local2'   => 'Number',
      'technical_professional_local3'   => 'Number',
      'technical_professional_local4'   => 'Number',
      'technical_professional_local5'   => 'Number',
      'technical_professional_foreign1' => 'Number',
      'technical_professional_foreign2' => 'Number',
      'technical_professional_foreign3' => 'Number',
      'technical_professional_foreign4' => 'Number',
      'technical_professional_foreign5' => 'Number',
      'skilled_labour_local1'           => 'Number',
      'skilled_labour_local2'           => 'Number',
      'skilled_labour_local3'           => 'Number',
      'skilled_labour_local4'           => 'Number',
      'skilled_labour_local5'           => 'Number',
      'skilled_labour_foreign1'         => 'Number',
      'skilled_labour_foreign2'         => 'Number',
      'skilled_labour_foreign3'         => 'Number',
      'skilled_labour_foreign4'         => 'Number',
      'skilled_labour_foreign5'         => 'Number',
      'other_jobs_local1'               => 'Number',
      'other_jobs_local2'               => 'Number',
      'other_jobs_local3'               => 'Number',
      'other_jobs_local4'               => 'Number',
      'other_jobs_local5'               => 'Number',
      'other_jobs_foreign1'             => 'Number',
      'other_jobs_foreign2'             => 'Number',
      'other_jobs_foreign3'             => 'Number',
      'other_jobs_foreign4'             => 'Number',
      'other_jobs_foreign5'             => 'Number',
      'sales_income1'                   => 'Number',
      'sales_income2'                   => 'Number',
      'sales_income3'                   => 'Number',
      'sales_income4'                   => 'Number',
      'sales_income5'                   => 'Number',
      'total_cost_sales1'               => 'Number',
      'total_cost_sales2'               => 'Number',
      'total_cost_sales3'               => 'Number',
      'total_cost_sales4'               => 'Number',
      'total_cost_sales5'               => 'Number',
      'gross_profit1'                   => 'Number',
      'gross_profit2'                   => 'Number',
      'gross_profit3'                   => 'Number',
      'gross_profit4'                   => 'Number',
      'gross_profit5'                   => 'Number',
      'indirect_expenses1'              => 'Number',
      'indirect_expenses2'              => 'Number',
      'indirect_expenses3'              => 'Number',
      'indirect_expenses4'              => 'Number',
      'indirect_expenses5'              => 'Number',
      'profit_before_tax1'              => 'Number',
      'profit_before_tax2'              => 'Number',
      'profit_before_tax3'              => 'Number',
      'profit_before_tax4'              => 'Number',
      'profit_before_tax5'              => 'Number',
      'tax_expenses1'                   => 'Number',
      'tax_expenses2'                   => 'Number',
      'tax_expenses3'                   => 'Number',
      'tax_expenses4'                   => 'Number',
      'tax_expenses5'                   => 'Number',
      'net_profit1'                     => 'Number',
      'net_profit2'                     => 'Number',
      'net_profit3'                     => 'Number',
      'net_profit4'                     => 'Number',
      'net_profit5'                     => 'Number',
      'project_brief'                   => 'Text',
      'exemption_on_machinery'          => 'Text',
      'exemption_raw_materials'         => 'Text',
      'land_ownership_document'         => 'Text',
      'bill_of_quantiy'                 => 'Text',
      'drawings'                        => 'Text',
      'construction_permits'            => 'Text',
      'investment_allowances'           => 'Text',
      'additional_incentives'           => 'Text',
      'visa_work_permits'               => 'Text',
      'created_at'                      => 'Date',
      'updated_at'                      => 'Date',
      'created_by'                      => 'ForeignKey',
      'updated_by'                      => 'Text',
    );
  }
}
