<?php

/**
 * BaseBusinessPlan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $investment_id
 * @property integer $land_year1
 * @property integer $land_year2
 * @property integer $land_year3
 * @property integer $land_year4
 * @property integer $land_year5
 * @property integer $construction_year1
 * @property integer $construction_year2
 * @property integer $construction_year3
 * @property integer $construction_year4
 * @property integer $construction_year5
 * @property integer $machinery_year1
 * @property integer $machinery_year2
 * @property integer $machinery_year3
 * @property integer $machinery_year4
 * @property integer $machinery_year5
 * @property integer $furniture_year1
 * @property integer $furniture_year2
 * @property integer $furniture_year3
 * @property integer $furniture_year4
 * @property integer $furniture_year5
 * @property integer $other_assets1
 * @property integer $other_assets2
 * @property integer $other_assets3
 * @property integer $other_assets4
 * @property integer $other_assets5
 * @property integer $studies_year1
 * @property integer $studies_year2
 * @property integer $studies_year3
 * @property integer $studies_year4
 * @property integer $studies_year5
 * @property integer $travel_expenses1
 * @property integer $travel_expenses2
 * @property integer $travel_expenses3
 * @property integer $travel_expenses4
 * @property integer $travel_expenses5
 * @property integer $starting_capital1
 * @property integer $starting_capital2
 * @property integer $starting_capital3
 * @property integer $starting_capital4
 * @property integer $starting_capital5
 * @property integer $licensing_expenses1
 * @property integer $licensing_expenses2
 * @property integer $licensing_expenses3
 * @property integer $licensing_expenses4
 * @property integer $licensing_expenses5
 * @property integer $rental_fees1
 * @property integer $rental_fees2
 * @property integer $rental_fees3
 * @property integer $rental_fees4
 * @property integer $rental_fees5
 * @property integer $other_expeses1
 * @property integer $other_expeses2
 * @property integer $other_expeses3
 * @property integer $other_expeses4
 * @property integer $other_expeses5
 * @property integer $equity_local
 * @property integer $equity_foregin
 * @property integer $bank_loan_local
 * @property integer $bank_loan_foreign
 * @property integer $mother_company_loan_local
 * @property integer $mother_company_loan_foreign
 * @property integer $grant_local
 * @property integer $grant_foreign
 * @property integer $top_management_local1
 * @property integer $top_management_local2
 * @property integer $top_management_local3
 * @property integer $top_management_local4
 * @property integer $top_management_local5
 * @property integer $top_management_foreign1
 * @property integer $top_management_foreign2
 * @property integer $top_management_foreign3
 * @property integer $top_management_foreign4
 * @property integer $top_management_foreign5
 * @property integer $technical_professional_local1
 * @property integer $technical_professional_local2
 * @property integer $technical_professional_local3
 * @property integer $technical_professional_local4
 * @property integer $technical_professional_local5
 * @property integer $technical_professional_foreign1
 * @property integer $technical_professional_foreign2
 * @property integer $technical_professional_foreign3
 * @property integer $technical_professional_foreign4
 * @property integer $technical_professional_foreign5
 * @property integer $skilled_labour_local1
 * @property integer $skilled_labour_local2
 * @property integer $skilled_labour_local3
 * @property integer $skilled_labour_local4
 * @property integer $skilled_labour_local5
 * @property integer $skilled_labour_foreign1
 * @property integer $skilled_labour_foreign2
 * @property integer $skilled_labour_foreign3
 * @property integer $skilled_labour_foreign4
 * @property integer $skilled_labour_foreign5
 * @property integer $other_jobs_local1
 * @property integer $other_jobs_local2
 * @property integer $other_jobs_local3
 * @property integer $other_jobs_local4
 * @property integer $other_jobs_local5
 * @property integer $other_jobs_foreign1
 * @property integer $other_jobs_foreign2
 * @property integer $other_jobs_foreign3
 * @property integer $other_jobs_foreign4
 * @property integer $other_jobs_foreign5
 * @property integer $sales_income1
 * @property integer $sales_income2
 * @property integer $sales_income3
 * @property integer $sales_income4
 * @property integer $sales_income5
 * @property integer $total_cost_sales1
 * @property integer $total_cost_sales2
 * @property integer $total_cost_sales3
 * @property integer $total_cost_sales4
 * @property integer $total_cost_sales5
 * @property integer $gross_profit1
 * @property integer $gross_profit2
 * @property integer $gross_profit3
 * @property integer $gross_profit4
 * @property integer $gross_profit5
 * @property integer $indirect_expenses1
 * @property integer $indirect_expenses2
 * @property integer $indirect_expenses3
 * @property integer $indirect_expenses4
 * @property integer $indirect_expenses5
 * @property integer $profit_before_tax1
 * @property integer $profit_before_tax2
 * @property integer $profit_before_tax3
 * @property integer $profit_before_tax4
 * @property integer $profit_before_tax5
 * @property integer $tax_expenses1
 * @property integer $tax_expenses2
 * @property integer $tax_expenses3
 * @property integer $tax_expenses4
 * @property integer $tax_expenses5
 * @property integer $net_profit1
 * @property integer $net_profit2
 * @property integer $net_profit3
 * @property integer $net_profit4
 * @property integer $net_profit5
 * @property string $project_brief
 * @property string $exemption_on_machinery
 * @property string $exemption_raw_materials
 * @property string $land_ownership_document
 * @property string $bill_of_quantiy
 * @property string $drawings
 * @property string $construction_permits
 * @property string $investment_allowances
 * @property string $additional_incentives
 * @property string $visa_work_permits
 * @property InvestmentApplication $InvestmentApplication
 * 
 * @method integer               getInvestmentId()                    Returns the current record's "investment_id" value
 * @method integer               getLandYear1()                       Returns the current record's "land_year1" value
 * @method integer               getLandYear2()                       Returns the current record's "land_year2" value
 * @method integer               getLandYear3()                       Returns the current record's "land_year3" value
 * @method integer               getLandYear4()                       Returns the current record's "land_year4" value
 * @method integer               getLandYear5()                       Returns the current record's "land_year5" value
 * @method integer               getConstructionYear1()               Returns the current record's "construction_year1" value
 * @method integer               getConstructionYear2()               Returns the current record's "construction_year2" value
 * @method integer               getConstructionYear3()               Returns the current record's "construction_year3" value
 * @method integer               getConstructionYear4()               Returns the current record's "construction_year4" value
 * @method integer               getConstructionYear5()               Returns the current record's "construction_year5" value
 * @method integer               getMachineryYear1()                  Returns the current record's "machinery_year1" value
 * @method integer               getMachineryYear2()                  Returns the current record's "machinery_year2" value
 * @method integer               getMachineryYear3()                  Returns the current record's "machinery_year3" value
 * @method integer               getMachineryYear4()                  Returns the current record's "machinery_year4" value
 * @method integer               getMachineryYear5()                  Returns the current record's "machinery_year5" value
 * @method integer               getFurnitureYear1()                  Returns the current record's "furniture_year1" value
 * @method integer               getFurnitureYear2()                  Returns the current record's "furniture_year2" value
 * @method integer               getFurnitureYear3()                  Returns the current record's "furniture_year3" value
 * @method integer               getFurnitureYear4()                  Returns the current record's "furniture_year4" value
 * @method integer               getFurnitureYear5()                  Returns the current record's "furniture_year5" value
 * @method integer               getOtherAssets1()                    Returns the current record's "other_assets1" value
 * @method integer               getOtherAssets2()                    Returns the current record's "other_assets2" value
 * @method integer               getOtherAssets3()                    Returns the current record's "other_assets3" value
 * @method integer               getOtherAssets4()                    Returns the current record's "other_assets4" value
 * @method integer               getOtherAssets5()                    Returns the current record's "other_assets5" value
 * @method integer               getStudiesYear1()                    Returns the current record's "studies_year1" value
 * @method integer               getStudiesYear2()                    Returns the current record's "studies_year2" value
 * @method integer               getStudiesYear3()                    Returns the current record's "studies_year3" value
 * @method integer               getStudiesYear4()                    Returns the current record's "studies_year4" value
 * @method integer               getStudiesYear5()                    Returns the current record's "studies_year5" value
 * @method integer               getTravelExpenses1()                 Returns the current record's "travel_expenses1" value
 * @method integer               getTravelExpenses2()                 Returns the current record's "travel_expenses2" value
 * @method integer               getTravelExpenses3()                 Returns the current record's "travel_expenses3" value
 * @method integer               getTravelExpenses4()                 Returns the current record's "travel_expenses4" value
 * @method integer               getTravelExpenses5()                 Returns the current record's "travel_expenses5" value
 * @method integer               getStartingCapital1()                Returns the current record's "starting_capital1" value
 * @method integer               getStartingCapital2()                Returns the current record's "starting_capital2" value
 * @method integer               getStartingCapital3()                Returns the current record's "starting_capital3" value
 * @method integer               getStartingCapital4()                Returns the current record's "starting_capital4" value
 * @method integer               getStartingCapital5()                Returns the current record's "starting_capital5" value
 * @method integer               getLicensingExpenses1()              Returns the current record's "licensing_expenses1" value
 * @method integer               getLicensingExpenses2()              Returns the current record's "licensing_expenses2" value
 * @method integer               getLicensingExpenses3()              Returns the current record's "licensing_expenses3" value
 * @method integer               getLicensingExpenses4()              Returns the current record's "licensing_expenses4" value
 * @method integer               getLicensingExpenses5()              Returns the current record's "licensing_expenses5" value
 * @method integer               getRentalFees1()                     Returns the current record's "rental_fees1" value
 * @method integer               getRentalFees2()                     Returns the current record's "rental_fees2" value
 * @method integer               getRentalFees3()                     Returns the current record's "rental_fees3" value
 * @method integer               getRentalFees4()                     Returns the current record's "rental_fees4" value
 * @method integer               getRentalFees5()                     Returns the current record's "rental_fees5" value
 * @method integer               getOtherExpeses1()                   Returns the current record's "other_expeses1" value
 * @method integer               getOtherExpeses2()                   Returns the current record's "other_expeses2" value
 * @method integer               getOtherExpeses3()                   Returns the current record's "other_expeses3" value
 * @method integer               getOtherExpeses4()                   Returns the current record's "other_expeses4" value
 * @method integer               getOtherExpeses5()                   Returns the current record's "other_expeses5" value
 * @method integer               getEquityLocal()                     Returns the current record's "equity_local" value
 * @method integer               getEquityForegin()                   Returns the current record's "equity_foregin" value
 * @method integer               getBankLoanLocal()                   Returns the current record's "bank_loan_local" value
 * @method integer               getBankLoanForeign()                 Returns the current record's "bank_loan_foreign" value
 * @method integer               getMotherCompanyLoanLocal()          Returns the current record's "mother_company_loan_local" value
 * @method integer               getMotherCompanyLoanForeign()        Returns the current record's "mother_company_loan_foreign" value
 * @method integer               getGrantLocal()                      Returns the current record's "grant_local" value
 * @method integer               getGrantForeign()                    Returns the current record's "grant_foreign" value
 * @method integer               getTopManagementLocal1()             Returns the current record's "top_management_local1" value
 * @method integer               getTopManagementLocal2()             Returns the current record's "top_management_local2" value
 * @method integer               getTopManagementLocal3()             Returns the current record's "top_management_local3" value
 * @method integer               getTopManagementLocal4()             Returns the current record's "top_management_local4" value
 * @method integer               getTopManagementLocal5()             Returns the current record's "top_management_local5" value
 * @method integer               getTopManagementForeign1()           Returns the current record's "top_management_foreign1" value
 * @method integer               getTopManagementForeign2()           Returns the current record's "top_management_foreign2" value
 * @method integer               getTopManagementForeign3()           Returns the current record's "top_management_foreign3" value
 * @method integer               getTopManagementForeign4()           Returns the current record's "top_management_foreign4" value
 * @method integer               getTopManagementForeign5()           Returns the current record's "top_management_foreign5" value
 * @method integer               getTechnicalProfessionalLocal1()     Returns the current record's "technical_professional_local1" value
 * @method integer               getTechnicalProfessionalLocal2()     Returns the current record's "technical_professional_local2" value
 * @method integer               getTechnicalProfessionalLocal3()     Returns the current record's "technical_professional_local3" value
 * @method integer               getTechnicalProfessionalLocal4()     Returns the current record's "technical_professional_local4" value
 * @method integer               getTechnicalProfessionalLocal5()     Returns the current record's "technical_professional_local5" value
 * @method integer               getTechnicalProfessionalForeign1()   Returns the current record's "technical_professional_foreign1" value
 * @method integer               getTechnicalProfessionalForeign2()   Returns the current record's "technical_professional_foreign2" value
 * @method integer               getTechnicalProfessionalForeign3()   Returns the current record's "technical_professional_foreign3" value
 * @method integer               getTechnicalProfessionalForeign4()   Returns the current record's "technical_professional_foreign4" value
 * @method integer               getTechnicalProfessionalForeign5()   Returns the current record's "technical_professional_foreign5" value
 * @method integer               getSkilledLabourLocal1()             Returns the current record's "skilled_labour_local1" value
 * @method integer               getSkilledLabourLocal2()             Returns the current record's "skilled_labour_local2" value
 * @method integer               getSkilledLabourLocal3()             Returns the current record's "skilled_labour_local3" value
 * @method integer               getSkilledLabourLocal4()             Returns the current record's "skilled_labour_local4" value
 * @method integer               getSkilledLabourLocal5()             Returns the current record's "skilled_labour_local5" value
 * @method integer               getSkilledLabourForeign1()           Returns the current record's "skilled_labour_foreign1" value
 * @method integer               getSkilledLabourForeign2()           Returns the current record's "skilled_labour_foreign2" value
 * @method integer               getSkilledLabourForeign3()           Returns the current record's "skilled_labour_foreign3" value
 * @method integer               getSkilledLabourForeign4()           Returns the current record's "skilled_labour_foreign4" value
 * @method integer               getSkilledLabourForeign5()           Returns the current record's "skilled_labour_foreign5" value
 * @method integer               getOtherJobsLocal1()                 Returns the current record's "other_jobs_local1" value
 * @method integer               getOtherJobsLocal2()                 Returns the current record's "other_jobs_local2" value
 * @method integer               getOtherJobsLocal3()                 Returns the current record's "other_jobs_local3" value
 * @method integer               getOtherJobsLocal4()                 Returns the current record's "other_jobs_local4" value
 * @method integer               getOtherJobsLocal5()                 Returns the current record's "other_jobs_local5" value
 * @method integer               getOtherJobsForeign1()               Returns the current record's "other_jobs_foreign1" value
 * @method integer               getOtherJobsForeign2()               Returns the current record's "other_jobs_foreign2" value
 * @method integer               getOtherJobsForeign3()               Returns the current record's "other_jobs_foreign3" value
 * @method integer               getOtherJobsForeign4()               Returns the current record's "other_jobs_foreign4" value
 * @method integer               getOtherJobsForeign5()               Returns the current record's "other_jobs_foreign5" value
 * @method integer               getSalesIncome1()                    Returns the current record's "sales_income1" value
 * @method integer               getSalesIncome2()                    Returns the current record's "sales_income2" value
 * @method integer               getSalesIncome3()                    Returns the current record's "sales_income3" value
 * @method integer               getSalesIncome4()                    Returns the current record's "sales_income4" value
 * @method integer               getSalesIncome5()                    Returns the current record's "sales_income5" value
 * @method integer               getTotalCostSales1()                 Returns the current record's "total_cost_sales1" value
 * @method integer               getTotalCostSales2()                 Returns the current record's "total_cost_sales2" value
 * @method integer               getTotalCostSales3()                 Returns the current record's "total_cost_sales3" value
 * @method integer               getTotalCostSales4()                 Returns the current record's "total_cost_sales4" value
 * @method integer               getTotalCostSales5()                 Returns the current record's "total_cost_sales5" value
 * @method integer               getGrossProfit1()                    Returns the current record's "gross_profit1" value
 * @method integer               getGrossProfit2()                    Returns the current record's "gross_profit2" value
 * @method integer               getGrossProfit3()                    Returns the current record's "gross_profit3" value
 * @method integer               getGrossProfit4()                    Returns the current record's "gross_profit4" value
 * @method integer               getGrossProfit5()                    Returns the current record's "gross_profit5" value
 * @method integer               getIndirectExpenses1()               Returns the current record's "indirect_expenses1" value
 * @method integer               getIndirectExpenses2()               Returns the current record's "indirect_expenses2" value
 * @method integer               getIndirectExpenses3()               Returns the current record's "indirect_expenses3" value
 * @method integer               getIndirectExpenses4()               Returns the current record's "indirect_expenses4" value
 * @method integer               getIndirectExpenses5()               Returns the current record's "indirect_expenses5" value
 * @method integer               getProfitBeforeTax1()                Returns the current record's "profit_before_tax1" value
 * @method integer               getProfitBeforeTax2()                Returns the current record's "profit_before_tax2" value
 * @method integer               getProfitBeforeTax3()                Returns the current record's "profit_before_tax3" value
 * @method integer               getProfitBeforeTax4()                Returns the current record's "profit_before_tax4" value
 * @method integer               getProfitBeforeTax5()                Returns the current record's "profit_before_tax5" value
 * @method integer               getTaxExpenses1()                    Returns the current record's "tax_expenses1" value
 * @method integer               getTaxExpenses2()                    Returns the current record's "tax_expenses2" value
 * @method integer               getTaxExpenses3()                    Returns the current record's "tax_expenses3" value
 * @method integer               getTaxExpenses4()                    Returns the current record's "tax_expenses4" value
 * @method integer               getTaxExpenses5()                    Returns the current record's "tax_expenses5" value
 * @method integer               getNetProfit1()                      Returns the current record's "net_profit1" value
 * @method integer               getNetProfit2()                      Returns the current record's "net_profit2" value
 * @method integer               getNetProfit3()                      Returns the current record's "net_profit3" value
 * @method integer               getNetProfit4()                      Returns the current record's "net_profit4" value
 * @method integer               getNetProfit5()                      Returns the current record's "net_profit5" value
 * @method string                getProjectBrief()                    Returns the current record's "project_brief" value
 * @method string                getExemptionOnMachinery()            Returns the current record's "exemption_on_machinery" value
 * @method string                getExemptionRawMaterials()           Returns the current record's "exemption_raw_materials" value
 * @method string                getLandOwnershipDocument()           Returns the current record's "land_ownership_document" value
 * @method string                getBillOfQuantiy()                   Returns the current record's "bill_of_quantiy" value
 * @method string                getDrawings()                        Returns the current record's "drawings" value
 * @method string                getConstructionPermits()             Returns the current record's "construction_permits" value
 * @method string                getInvestmentAllowances()            Returns the current record's "investment_allowances" value
 * @method string                getAdditionalIncentives()            Returns the current record's "additional_incentives" value
 * @method string                getVisaWorkPermits()                 Returns the current record's "visa_work_permits" value
 * @method InvestmentApplication getInvestmentApplication()           Returns the current record's "InvestmentApplication" value
 * @method BusinessPlan          setInvestmentId()                    Sets the current record's "investment_id" value
 * @method BusinessPlan          setLandYear1()                       Sets the current record's "land_year1" value
 * @method BusinessPlan          setLandYear2()                       Sets the current record's "land_year2" value
 * @method BusinessPlan          setLandYear3()                       Sets the current record's "land_year3" value
 * @method BusinessPlan          setLandYear4()                       Sets the current record's "land_year4" value
 * @method BusinessPlan          setLandYear5()                       Sets the current record's "land_year5" value
 * @method BusinessPlan          setConstructionYear1()               Sets the current record's "construction_year1" value
 * @method BusinessPlan          setConstructionYear2()               Sets the current record's "construction_year2" value
 * @method BusinessPlan          setConstructionYear3()               Sets the current record's "construction_year3" value
 * @method BusinessPlan          setConstructionYear4()               Sets the current record's "construction_year4" value
 * @method BusinessPlan          setConstructionYear5()               Sets the current record's "construction_year5" value
 * @method BusinessPlan          setMachineryYear1()                  Sets the current record's "machinery_year1" value
 * @method BusinessPlan          setMachineryYear2()                  Sets the current record's "machinery_year2" value
 * @method BusinessPlan          setMachineryYear3()                  Sets the current record's "machinery_year3" value
 * @method BusinessPlan          setMachineryYear4()                  Sets the current record's "machinery_year4" value
 * @method BusinessPlan          setMachineryYear5()                  Sets the current record's "machinery_year5" value
 * @method BusinessPlan          setFurnitureYear1()                  Sets the current record's "furniture_year1" value
 * @method BusinessPlan          setFurnitureYear2()                  Sets the current record's "furniture_year2" value
 * @method BusinessPlan          setFurnitureYear3()                  Sets the current record's "furniture_year3" value
 * @method BusinessPlan          setFurnitureYear4()                  Sets the current record's "furniture_year4" value
 * @method BusinessPlan          setFurnitureYear5()                  Sets the current record's "furniture_year5" value
 * @method BusinessPlan          setOtherAssets1()                    Sets the current record's "other_assets1" value
 * @method BusinessPlan          setOtherAssets2()                    Sets the current record's "other_assets2" value
 * @method BusinessPlan          setOtherAssets3()                    Sets the current record's "other_assets3" value
 * @method BusinessPlan          setOtherAssets4()                    Sets the current record's "other_assets4" value
 * @method BusinessPlan          setOtherAssets5()                    Sets the current record's "other_assets5" value
 * @method BusinessPlan          setStudiesYear1()                    Sets the current record's "studies_year1" value
 * @method BusinessPlan          setStudiesYear2()                    Sets the current record's "studies_year2" value
 * @method BusinessPlan          setStudiesYear3()                    Sets the current record's "studies_year3" value
 * @method BusinessPlan          setStudiesYear4()                    Sets the current record's "studies_year4" value
 * @method BusinessPlan          setStudiesYear5()                    Sets the current record's "studies_year5" value
 * @method BusinessPlan          setTravelExpenses1()                 Sets the current record's "travel_expenses1" value
 * @method BusinessPlan          setTravelExpenses2()                 Sets the current record's "travel_expenses2" value
 * @method BusinessPlan          setTravelExpenses3()                 Sets the current record's "travel_expenses3" value
 * @method BusinessPlan          setTravelExpenses4()                 Sets the current record's "travel_expenses4" value
 * @method BusinessPlan          setTravelExpenses5()                 Sets the current record's "travel_expenses5" value
 * @method BusinessPlan          setStartingCapital1()                Sets the current record's "starting_capital1" value
 * @method BusinessPlan          setStartingCapital2()                Sets the current record's "starting_capital2" value
 * @method BusinessPlan          setStartingCapital3()                Sets the current record's "starting_capital3" value
 * @method BusinessPlan          setStartingCapital4()                Sets the current record's "starting_capital4" value
 * @method BusinessPlan          setStartingCapital5()                Sets the current record's "starting_capital5" value
 * @method BusinessPlan          setLicensingExpenses1()              Sets the current record's "licensing_expenses1" value
 * @method BusinessPlan          setLicensingExpenses2()              Sets the current record's "licensing_expenses2" value
 * @method BusinessPlan          setLicensingExpenses3()              Sets the current record's "licensing_expenses3" value
 * @method BusinessPlan          setLicensingExpenses4()              Sets the current record's "licensing_expenses4" value
 * @method BusinessPlan          setLicensingExpenses5()              Sets the current record's "licensing_expenses5" value
 * @method BusinessPlan          setRentalFees1()                     Sets the current record's "rental_fees1" value
 * @method BusinessPlan          setRentalFees2()                     Sets the current record's "rental_fees2" value
 * @method BusinessPlan          setRentalFees3()                     Sets the current record's "rental_fees3" value
 * @method BusinessPlan          setRentalFees4()                     Sets the current record's "rental_fees4" value
 * @method BusinessPlan          setRentalFees5()                     Sets the current record's "rental_fees5" value
 * @method BusinessPlan          setOtherExpeses1()                   Sets the current record's "other_expeses1" value
 * @method BusinessPlan          setOtherExpeses2()                   Sets the current record's "other_expeses2" value
 * @method BusinessPlan          setOtherExpeses3()                   Sets the current record's "other_expeses3" value
 * @method BusinessPlan          setOtherExpeses4()                   Sets the current record's "other_expeses4" value
 * @method BusinessPlan          setOtherExpeses5()                   Sets the current record's "other_expeses5" value
 * @method BusinessPlan          setEquityLocal()                     Sets the current record's "equity_local" value
 * @method BusinessPlan          setEquityForegin()                   Sets the current record's "equity_foregin" value
 * @method BusinessPlan          setBankLoanLocal()                   Sets the current record's "bank_loan_local" value
 * @method BusinessPlan          setBankLoanForeign()                 Sets the current record's "bank_loan_foreign" value
 * @method BusinessPlan          setMotherCompanyLoanLocal()          Sets the current record's "mother_company_loan_local" value
 * @method BusinessPlan          setMotherCompanyLoanForeign()        Sets the current record's "mother_company_loan_foreign" value
 * @method BusinessPlan          setGrantLocal()                      Sets the current record's "grant_local" value
 * @method BusinessPlan          setGrantForeign()                    Sets the current record's "grant_foreign" value
 * @method BusinessPlan          setTopManagementLocal1()             Sets the current record's "top_management_local1" value
 * @method BusinessPlan          setTopManagementLocal2()             Sets the current record's "top_management_local2" value
 * @method BusinessPlan          setTopManagementLocal3()             Sets the current record's "top_management_local3" value
 * @method BusinessPlan          setTopManagementLocal4()             Sets the current record's "top_management_local4" value
 * @method BusinessPlan          setTopManagementLocal5()             Sets the current record's "top_management_local5" value
 * @method BusinessPlan          setTopManagementForeign1()           Sets the current record's "top_management_foreign1" value
 * @method BusinessPlan          setTopManagementForeign2()           Sets the current record's "top_management_foreign2" value
 * @method BusinessPlan          setTopManagementForeign3()           Sets the current record's "top_management_foreign3" value
 * @method BusinessPlan          setTopManagementForeign4()           Sets the current record's "top_management_foreign4" value
 * @method BusinessPlan          setTopManagementForeign5()           Sets the current record's "top_management_foreign5" value
 * @method BusinessPlan          setTechnicalProfessionalLocal1()     Sets the current record's "technical_professional_local1" value
 * @method BusinessPlan          setTechnicalProfessionalLocal2()     Sets the current record's "technical_professional_local2" value
 * @method BusinessPlan          setTechnicalProfessionalLocal3()     Sets the current record's "technical_professional_local3" value
 * @method BusinessPlan          setTechnicalProfessionalLocal4()     Sets the current record's "technical_professional_local4" value
 * @method BusinessPlan          setTechnicalProfessionalLocal5()     Sets the current record's "technical_professional_local5" value
 * @method BusinessPlan          setTechnicalProfessionalForeign1()   Sets the current record's "technical_professional_foreign1" value
 * @method BusinessPlan          setTechnicalProfessionalForeign2()   Sets the current record's "technical_professional_foreign2" value
 * @method BusinessPlan          setTechnicalProfessionalForeign3()   Sets the current record's "technical_professional_foreign3" value
 * @method BusinessPlan          setTechnicalProfessionalForeign4()   Sets the current record's "technical_professional_foreign4" value
 * @method BusinessPlan          setTechnicalProfessionalForeign5()   Sets the current record's "technical_professional_foreign5" value
 * @method BusinessPlan          setSkilledLabourLocal1()             Sets the current record's "skilled_labour_local1" value
 * @method BusinessPlan          setSkilledLabourLocal2()             Sets the current record's "skilled_labour_local2" value
 * @method BusinessPlan          setSkilledLabourLocal3()             Sets the current record's "skilled_labour_local3" value
 * @method BusinessPlan          setSkilledLabourLocal4()             Sets the current record's "skilled_labour_local4" value
 * @method BusinessPlan          setSkilledLabourLocal5()             Sets the current record's "skilled_labour_local5" value
 * @method BusinessPlan          setSkilledLabourForeign1()           Sets the current record's "skilled_labour_foreign1" value
 * @method BusinessPlan          setSkilledLabourForeign2()           Sets the current record's "skilled_labour_foreign2" value
 * @method BusinessPlan          setSkilledLabourForeign3()           Sets the current record's "skilled_labour_foreign3" value
 * @method BusinessPlan          setSkilledLabourForeign4()           Sets the current record's "skilled_labour_foreign4" value
 * @method BusinessPlan          setSkilledLabourForeign5()           Sets the current record's "skilled_labour_foreign5" value
 * @method BusinessPlan          setOtherJobsLocal1()                 Sets the current record's "other_jobs_local1" value
 * @method BusinessPlan          setOtherJobsLocal2()                 Sets the current record's "other_jobs_local2" value
 * @method BusinessPlan          setOtherJobsLocal3()                 Sets the current record's "other_jobs_local3" value
 * @method BusinessPlan          setOtherJobsLocal4()                 Sets the current record's "other_jobs_local4" value
 * @method BusinessPlan          setOtherJobsLocal5()                 Sets the current record's "other_jobs_local5" value
 * @method BusinessPlan          setOtherJobsForeign1()               Sets the current record's "other_jobs_foreign1" value
 * @method BusinessPlan          setOtherJobsForeign2()               Sets the current record's "other_jobs_foreign2" value
 * @method BusinessPlan          setOtherJobsForeign3()               Sets the current record's "other_jobs_foreign3" value
 * @method BusinessPlan          setOtherJobsForeign4()               Sets the current record's "other_jobs_foreign4" value
 * @method BusinessPlan          setOtherJobsForeign5()               Sets the current record's "other_jobs_foreign5" value
 * @method BusinessPlan          setSalesIncome1()                    Sets the current record's "sales_income1" value
 * @method BusinessPlan          setSalesIncome2()                    Sets the current record's "sales_income2" value
 * @method BusinessPlan          setSalesIncome3()                    Sets the current record's "sales_income3" value
 * @method BusinessPlan          setSalesIncome4()                    Sets the current record's "sales_income4" value
 * @method BusinessPlan          setSalesIncome5()                    Sets the current record's "sales_income5" value
 * @method BusinessPlan          setTotalCostSales1()                 Sets the current record's "total_cost_sales1" value
 * @method BusinessPlan          setTotalCostSales2()                 Sets the current record's "total_cost_sales2" value
 * @method BusinessPlan          setTotalCostSales3()                 Sets the current record's "total_cost_sales3" value
 * @method BusinessPlan          setTotalCostSales4()                 Sets the current record's "total_cost_sales4" value
 * @method BusinessPlan          setTotalCostSales5()                 Sets the current record's "total_cost_sales5" value
 * @method BusinessPlan          setGrossProfit1()                    Sets the current record's "gross_profit1" value
 * @method BusinessPlan          setGrossProfit2()                    Sets the current record's "gross_profit2" value
 * @method BusinessPlan          setGrossProfit3()                    Sets the current record's "gross_profit3" value
 * @method BusinessPlan          setGrossProfit4()                    Sets the current record's "gross_profit4" value
 * @method BusinessPlan          setGrossProfit5()                    Sets the current record's "gross_profit5" value
 * @method BusinessPlan          setIndirectExpenses1()               Sets the current record's "indirect_expenses1" value
 * @method BusinessPlan          setIndirectExpenses2()               Sets the current record's "indirect_expenses2" value
 * @method BusinessPlan          setIndirectExpenses3()               Sets the current record's "indirect_expenses3" value
 * @method BusinessPlan          setIndirectExpenses4()               Sets the current record's "indirect_expenses4" value
 * @method BusinessPlan          setIndirectExpenses5()               Sets the current record's "indirect_expenses5" value
 * @method BusinessPlan          setProfitBeforeTax1()                Sets the current record's "profit_before_tax1" value
 * @method BusinessPlan          setProfitBeforeTax2()                Sets the current record's "profit_before_tax2" value
 * @method BusinessPlan          setProfitBeforeTax3()                Sets the current record's "profit_before_tax3" value
 * @method BusinessPlan          setProfitBeforeTax4()                Sets the current record's "profit_before_tax4" value
 * @method BusinessPlan          setProfitBeforeTax5()                Sets the current record's "profit_before_tax5" value
 * @method BusinessPlan          setTaxExpenses1()                    Sets the current record's "tax_expenses1" value
 * @method BusinessPlan          setTaxExpenses2()                    Sets the current record's "tax_expenses2" value
 * @method BusinessPlan          setTaxExpenses3()                    Sets the current record's "tax_expenses3" value
 * @method BusinessPlan          setTaxExpenses4()                    Sets the current record's "tax_expenses4" value
 * @method BusinessPlan          setTaxExpenses5()                    Sets the current record's "tax_expenses5" value
 * @method BusinessPlan          setNetProfit1()                      Sets the current record's "net_profit1" value
 * @method BusinessPlan          setNetProfit2()                      Sets the current record's "net_profit2" value
 * @method BusinessPlan          setNetProfit3()                      Sets the current record's "net_profit3" value
 * @method BusinessPlan          setNetProfit4()                      Sets the current record's "net_profit4" value
 * @method BusinessPlan          setNetProfit5()                      Sets the current record's "net_profit5" value
 * @method BusinessPlan          setProjectBrief()                    Sets the current record's "project_brief" value
 * @method BusinessPlan          setExemptionOnMachinery()            Sets the current record's "exemption_on_machinery" value
 * @method BusinessPlan          setExemptionRawMaterials()           Sets the current record's "exemption_raw_materials" value
 * @method BusinessPlan          setLandOwnershipDocument()           Sets the current record's "land_ownership_document" value
 * @method BusinessPlan          setBillOfQuantiy()                   Sets the current record's "bill_of_quantiy" value
 * @method BusinessPlan          setDrawings()                        Sets the current record's "drawings" value
 * @method BusinessPlan          setConstructionPermits()             Sets the current record's "construction_permits" value
 * @method BusinessPlan          setInvestmentAllowances()            Sets the current record's "investment_allowances" value
 * @method BusinessPlan          setAdditionalIncentives()            Sets the current record's "additional_incentives" value
 * @method BusinessPlan          setVisaWorkPermits()                 Sets the current record's "visa_work_permits" value
 * @method BusinessPlan          setInvestmentApplication()           Sets the current record's "InvestmentApplication" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBusinessPlan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('business_plan');
        $this->hasColumn('investment_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('land_year1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('land_year2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('land_year3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('land_year4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('land_year5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('construction_year1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('construction_year2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('construction_year3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('construction_year4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('construction_year5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('machinery_year1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('machinery_year2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('machinery_year3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('machinery_year4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('machinery_year5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('furniture_year1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('furniture_year2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('furniture_year3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('furniture_year4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('furniture_year5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_assets1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_assets2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_assets3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_assets4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_assets5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('studies_year1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('studies_year2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('studies_year3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('studies_year4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('studies_year5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('travel_expenses1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('travel_expenses2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('travel_expenses3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('travel_expenses4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('travel_expenses5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('starting_capital1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('starting_capital2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('starting_capital3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('starting_capital4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('starting_capital5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('licensing_expenses1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('licensing_expenses2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('licensing_expenses3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('licensing_expenses4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('licensing_expenses5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('rental_fees1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('rental_fees2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('rental_fees3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('rental_fees4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('rental_fees5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_expeses1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_expeses2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_expeses3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_expeses4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_expeses5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('equity_local', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('equity_foregin', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('bank_loan_local', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('bank_loan_foreign', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('mother_company_loan_local', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('mother_company_loan_foreign', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('grant_local', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('grant_foreign', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_local1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_local2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_local3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_local4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_local5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_foreign1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_foreign2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_foreign3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_foreign4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('top_management_foreign5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_local1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_local2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_local3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_local4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_local5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_foreign1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_foreign2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_foreign3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_foreign4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('technical_professional_foreign5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_local1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_local2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_local3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_local4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_local5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_foreign1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_foreign2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_foreign3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_foreign4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('skilled_labour_foreign5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_local1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_local2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_local3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_local4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_local5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_foreign1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_foreign2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_foreign3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_foreign4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('other_jobs_foreign5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('sales_income1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('sales_income2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('sales_income3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('sales_income4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('sales_income5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('total_cost_sales1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('total_cost_sales2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('total_cost_sales3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('total_cost_sales4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('total_cost_sales5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('gross_profit1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('gross_profit2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('gross_profit3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('gross_profit4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('gross_profit5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('indirect_expenses1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('indirect_expenses2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('indirect_expenses3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('indirect_expenses4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('indirect_expenses5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('profit_before_tax1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('profit_before_tax2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('profit_before_tax3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('profit_before_tax4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('profit_before_tax5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tax_expenses1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tax_expenses2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tax_expenses3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tax_expenses4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tax_expenses5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('net_profit1', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('net_profit2', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('net_profit3', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('net_profit4', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('net_profit5', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('project_brief', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('exemption_on_machinery', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('exemption_raw_materials', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('land_ownership_document', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('bill_of_quantiy', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('drawings', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('construction_permits', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('investment_allowances', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('additional_incentives', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
        $this->hasColumn('visa_work_permits', 'string', 4000, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('InvestmentApplication', array(
             'local' => 'investment_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable(array(
             'created:{ name' => 'created_by,type: string,onUpdate: CASCADE,onDelete: SET NULL,options: {notnull: true,default: None}}',
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}