<?php

/**
 * BaseBusinessApplicationStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $business_id
 * @property string $application_status
 * @property string $comment
 * @property integer $percentage
 * @property InvestmentApplication $InvestmentApplication
 * 
 * @method integer                   getBusinessId()            Returns the current record's "business_id" value
 * @method string                    getApplicationStatus()     Returns the current record's "application_status" value
 * @method string                    getComment()               Returns the current record's "comment" value
 * @method integer                   getPercentage()            Returns the current record's "percentage" value
 * @method InvestmentApplication     getInvestmentApplication() Returns the current record's "InvestmentApplication" value
 * @method BusinessApplicationStatus setBusinessId()            Sets the current record's "business_id" value
 * @method BusinessApplicationStatus setApplicationStatus()     Sets the current record's "application_status" value
 * @method BusinessApplicationStatus setComment()               Sets the current record's "comment" value
 * @method BusinessApplicationStatus setPercentage()            Sets the current record's "percentage" value
 * @method BusinessApplicationStatus setInvestmentApplication() Sets the current record's "InvestmentApplication" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBusinessApplicationStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('business_application_status');
        $this->hasColumn('business_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('application_status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('comment', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('percentage', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('InvestmentApplication', array(
             'local' => 'business_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}