<?php

/**
 * BaseNotifications
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $recepient
 * @property string $message
 * 
 * @method string        getRecepient() Returns the current record's "recepient" value
 * @method string        getMessage()   Returns the current record's "message" value
 * @method Notifications setRecepient() Sets the current record's "recepient" value
 * @method Notifications setMessage()   Sets the current record's "message" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotifications extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notifications');
        $this->hasColumn('recepient', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('message', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}