<?php

/**
 * BaseProjectImpact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property string $impact_level
 * @property string $comments
 * @property EIApplication $EIApplication
 * @property Doctrine_Collection $EIAProjectImpact
 * 
 * @method integer             getCompanyId()        Returns the current record's "company_id" value
 * @method string              getImpactLevel()      Returns the current record's "impact_level" value
 * @method string              getComments()         Returns the current record's "comments" value
 * @method EIApplication       getEIApplication()    Returns the current record's "EIApplication" value
 * @method Doctrine_Collection getEIAProjectImpact() Returns the current record's "EIAProjectImpact" collection
 * @method ProjectImpact       setCompanyId()        Sets the current record's "company_id" value
 * @method ProjectImpact       setImpactLevel()      Sets the current record's "impact_level" value
 * @method ProjectImpact       setComments()         Sets the current record's "comments" value
 * @method ProjectImpact       setEIApplication()    Sets the current record's "EIApplication" value
 * @method ProjectImpact       setEIAProjectImpact() Sets the current record's "EIAProjectImpact" collection
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjectImpact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('project_impact');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('impact_level', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('comments', 'string', 400, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 400,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EIApplication', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Tor as EIAProjectImpact', array(
             'local' => 'id',
             'foreign' => 'impact_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable(array(
             'created:{ name' => 'created_by,type: string,onUpdate: CASCADE,onDelete: SET NULL,options: {notnull: true,default: None}}',
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}