<?php

/**
 * BaseEIAProjectDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_reference_number
 * @property string $project_title
 * @property string $project_plot_number
 * @property string $village
 * @property string $cell
 * @property string $sector
 * @property string $district
 * @property string $province
 * @property string $token
 * @property Doctrine_Collection $EIAProjectDeveloperDetails
 * @property Doctrine_Collection $EIAProjectDetailsDescription
 * @property Doctrine_Collection $EIAProjectDetailSurrounding
 * @property Doctrine_Collection $EIAProjectDetailSocialEconomic
 * @property Doctrine_Collection $EIAProjectDetailImpactMeasures
 * @property Doctrine_Collection $EIAProjectDetailOperationPhase
 * @property Doctrine_Collection $EIAProjectDetailAttachment
 * @property Doctrine_Collection $EIApplicationStatus
 * @property Doctrine_Collection $ApplicationBriefDecision
 * @property Doctrine_Collection $ApplicationAssigment
 * @property Doctrine_Collection $EIAProjectImpact
 * @property Doctrine_Collection $ApplicationImpactPass
 * @property Doctrine_Collection $ApplicationTorStatus
 * @property Doctrine_Collection $EIAStudyUploads
 * @property Doctrine_Collection $EIApplicationComments
 * 
 * @method integer             getProjectReferenceNumber()         Returns the current record's "project_reference_number" value
 * @method string              getProjectTitle()                   Returns the current record's "project_title" value
 * @method string              getProjectPlotNumber()              Returns the current record's "project_plot_number" value
 * @method string              getVillage()                        Returns the current record's "village" value
 * @method string              getCell()                           Returns the current record's "cell" value
 * @method string              getSector()                         Returns the current record's "sector" value
 * @method string              getDistrict()                       Returns the current record's "district" value
 * @method string              getProvince()                       Returns the current record's "province" value
 * @method string              getToken()                          Returns the current record's "token" value
 * @method Doctrine_Collection getEIAProjectDeveloperDetails()     Returns the current record's "EIAProjectDeveloperDetails" collection
 * @method Doctrine_Collection getEIAProjectDetailsDescription()   Returns the current record's "EIAProjectDetailsDescription" collection
 * @method Doctrine_Collection getEIAProjectDetailSurrounding()    Returns the current record's "EIAProjectDetailSurrounding" collection
 * @method Doctrine_Collection getEIAProjectDetailSocialEconomic() Returns the current record's "EIAProjectDetailSocialEconomic" collection
 * @method Doctrine_Collection getEIAProjectDetailImpactMeasures() Returns the current record's "EIAProjectDetailImpactMeasures" collection
 * @method Doctrine_Collection getEIAProjectDetailOperationPhase() Returns the current record's "EIAProjectDetailOperationPhase" collection
 * @method Doctrine_Collection getEIAProjectDetailAttachment()     Returns the current record's "EIAProjectDetailAttachment" collection
 * @method Doctrine_Collection getEIApplicationStatus()            Returns the current record's "EIApplicationStatus" collection
 * @method Doctrine_Collection getApplicationBriefDecision()       Returns the current record's "ApplicationBriefDecision" collection
 * @method Doctrine_Collection getApplicationAssigment()           Returns the current record's "ApplicationAssigment" collection
 * @method Doctrine_Collection getEIAProjectImpact()               Returns the current record's "EIAProjectImpact" collection
 * @method Doctrine_Collection getApplicationImpactPass()          Returns the current record's "ApplicationImpactPass" collection
 * @method Doctrine_Collection getApplicationTorStatus()           Returns the current record's "ApplicationTorStatus" collection
 * @method Doctrine_Collection getEIAStudyUploads()                Returns the current record's "EIAStudyUploads" collection
 * @method Doctrine_Collection getEIApplicationComments()          Returns the current record's "EIApplicationComments" collection
 * @method EIAProjectDetail    setProjectReferenceNumber()         Sets the current record's "project_reference_number" value
 * @method EIAProjectDetail    setProjectTitle()                   Sets the current record's "project_title" value
 * @method EIAProjectDetail    setProjectPlotNumber()              Sets the current record's "project_plot_number" value
 * @method EIAProjectDetail    setVillage()                        Sets the current record's "village" value
 * @method EIAProjectDetail    setCell()                           Sets the current record's "cell" value
 * @method EIAProjectDetail    setSector()                         Sets the current record's "sector" value
 * @method EIAProjectDetail    setDistrict()                       Sets the current record's "district" value
 * @method EIAProjectDetail    setProvince()                       Sets the current record's "province" value
 * @method EIAProjectDetail    setToken()                          Sets the current record's "token" value
 * @method EIAProjectDetail    setEIAProjectDeveloperDetails()     Sets the current record's "EIAProjectDeveloperDetails" collection
 * @method EIAProjectDetail    setEIAProjectDetailsDescription()   Sets the current record's "EIAProjectDetailsDescription" collection
 * @method EIAProjectDetail    setEIAProjectDetailSurrounding()    Sets the current record's "EIAProjectDetailSurrounding" collection
 * @method EIAProjectDetail    setEIAProjectDetailSocialEconomic() Sets the current record's "EIAProjectDetailSocialEconomic" collection
 * @method EIAProjectDetail    setEIAProjectDetailImpactMeasures() Sets the current record's "EIAProjectDetailImpactMeasures" collection
 * @method EIAProjectDetail    setEIAProjectDetailOperationPhase() Sets the current record's "EIAProjectDetailOperationPhase" collection
 * @method EIAProjectDetail    setEIAProjectDetailAttachment()     Sets the current record's "EIAProjectDetailAttachment" collection
 * @method EIAProjectDetail    setEIApplicationStatus()            Sets the current record's "EIApplicationStatus" collection
 * @method EIAProjectDetail    setApplicationBriefDecision()       Sets the current record's "ApplicationBriefDecision" collection
 * @method EIAProjectDetail    setApplicationAssigment()           Sets the current record's "ApplicationAssigment" collection
 * @method EIAProjectDetail    setEIAProjectImpact()               Sets the current record's "EIAProjectImpact" collection
 * @method EIAProjectDetail    setApplicationImpactPass()          Sets the current record's "ApplicationImpactPass" collection
 * @method EIAProjectDetail    setApplicationTorStatus()           Sets the current record's "ApplicationTorStatus" collection
 * @method EIAProjectDetail    setEIAStudyUploads()                Sets the current record's "EIAStudyUploads" collection
 * @method EIAProjectDetail    setEIApplicationComments()          Sets the current record's "EIApplicationComments" collection
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEIAProjectDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('e_i_a_project_detail');
        $this->hasColumn('project_reference_number', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('project_title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('project_plot_number', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('village', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('cell', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('sector', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('district', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('province', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EIAProjectDeveloper as EIAProjectDeveloperDetails', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIAProjectDescription as EIAProjectDetailsDescription', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIAProjectSurrounding as EIAProjectDetailSurrounding', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIAProjectSocialEconomic as EIAProjectDetailSocialEconomic', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIAProjectImpactMeasures as EIAProjectDetailImpactMeasures', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIAProjectOperationPhase as EIAProjectDetailOperationPhase', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIAProjectAttachment as EIAProjectDetailAttachment', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIApplicationStatus', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIAProjectBriefDecision as ApplicationBriefDecision', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EITaskAssignment as ApplicationAssigment', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('ProjectImpact as EIAProjectImpact', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIAProjectImpactPass as ApplicationImpactPass', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIATorStatus as ApplicationTorStatus', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIReport as EIAStudyUploads', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $this->hasMany('EIComments as EIApplicationComments', array(
             'local' => 'id',
             'foreign' => 'eiaproject_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable(array(
             'created:{ name' => 'created_by,type: string,onUpdate: CASCADE,onDelete: SET NULL,options: {notnull: true,default: None}}',
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}