<?php

/**
 * BasePortlets
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $investment_certificate
 * @property string $eia_certificate
 * @property string $tax_exemptions
 * 
 * @method string   getInvestmentCertificate()  Returns the current record's "investment_certificate" value
 * @method string   getEiaCertificate()         Returns the current record's "eia_certificate" value
 * @method string   getTaxExemptions()          Returns the current record's "tax_exemptions" value
 * @method Portlets setInvestmentCertificate()  Sets the current record's "investment_certificate" value
 * @method Portlets setEiaCertificate()         Sets the current record's "eia_certificate" value
 * @method Portlets setTaxExemptions()          Sets the current record's "tax_exemptions" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePortlets extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('portlets');
        $this->hasColumn('investment_certificate', 'string', 7000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 7000,
             ));
        $this->hasColumn('eia_certificate', 'string', 7000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 7000,
             ));
        $this->hasColumn('tax_exemptions', 'string', 7000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 7000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable(array(
             'created:{ name' => 'created_by,type: string,onUpdate: CASCADE,onDelete: SET NULL,options: {notnull: true,default: None}}',
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}