<?php

/**
 * BaseEIReportResubmission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eiaproject_id
 * @property string $status
 * @property string $comments
 * @property string $commets_doc
 * 
 * @method integer              getEiaprojectId()  Returns the current record's "eiaproject_id" value
 * @method string               getStatus()        Returns the current record's "status" value
 * @method string               getComments()      Returns the current record's "comments" value
 * @method string               getCommetsDoc()    Returns the current record's "commets_doc" value
 * @method EIReportResubmission setEiaprojectId()  Sets the current record's "eiaproject_id" value
 * @method EIReportResubmission setStatus()        Sets the current record's "status" value
 * @method EIReportResubmission setComments()      Sets the current record's "comments" value
 * @method EIReportResubmission setCommetsDoc()    Sets the current record's "commets_doc" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEIReportResubmission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('e_i_report_resubmission');
        $this->hasColumn('eiaproject_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('comments', 'string', 2000, array(
             'type' => 'string',
             'length' => '2000',
             ));
        $this->hasColumn('commets_doc', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable(array(
             'created:{ name' => 'created_by,type: string,onUpdate: CASCADE,onDelete: SET NULL,options: {notnull: true,default: None}}',
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}