<?php

/**
 * BaseEIApplicationStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eiaproject_id
 * @property string $application_status
 * @property string $comments
 * @property integer $percentage
 * @property string $token
 * @property EIAProjectDetail $EIAProjectDetail
 * 
 * @method integer             getEiaprojectId()       Returns the current record's "eiaproject_id" value
 * @method string              getApplicationStatus()  Returns the current record's "application_status" value
 * @method string              getComments()           Returns the current record's "comments" value
 * @method integer             getPercentage()         Returns the current record's "percentage" value
 * @method string              getToken()              Returns the current record's "token" value
 * @method EIAProjectDetail    getEIAProjectDetail()   Returns the current record's "EIAProjectDetail" value
 * @method EIApplicationStatus setEiaprojectId()       Sets the current record's "eiaproject_id" value
 * @method EIApplicationStatus setApplicationStatus()  Sets the current record's "application_status" value
 * @method EIApplicationStatus setComments()           Sets the current record's "comments" value
 * @method EIApplicationStatus setPercentage()         Sets the current record's "percentage" value
 * @method EIApplicationStatus setToken()              Sets the current record's "token" value
 * @method EIApplicationStatus setEIAProjectDetail()   Sets the current record's "EIAProjectDetail" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEIApplicationStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('e_i_application_status');
        $this->hasColumn('eiaproject_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('application_status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('comments', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('percentage', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EIAProjectDetail', array(
             'local' => 'eiaproject_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}