<?php

/**
 * BaseInvestmentCertificate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $serial_number
 * @property integer $business_id
 * @property InvestmentApplication $InvestmentApplication
 * 
 * @method integer               getSerialNumber()          Returns the current record's "serial_number" value
 * @method integer               getBusinessId()            Returns the current record's "business_id" value
 * @method InvestmentApplication getInvestmentApplication() Returns the current record's "InvestmentApplication" value
 * @method InvestmentCertificate setSerialNumber()          Sets the current record's "serial_number" value
 * @method InvestmentCertificate setBusinessId()            Sets the current record's "business_id" value
 * @method InvestmentCertificate setInvestmentApplication() Sets the current record's "InvestmentApplication" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvestmentCertificate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('investment_certificate');
        $this->hasColumn('serial_number', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('business_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('InvestmentApplication', array(
             'local' => 'business_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable(array(
             'created' => 
             array(
              'name' => 'created_by',
              'type' => 'string',
              'onUpdate' => 'CASCADE',
              'onDelete' => 'SET NULL',
              'options' => 
              array(
              'notnull' => true,
              'default' => 'None',
              ),
             ),
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}