<?php

/**
 * BaseTaskAssignment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_assigned
 * @property integer $investmentapp_id
 * @property string $instructions
 * @property timestamp $duedate
 * @property string $work_status
 * @property InvestmentApplication $InvestmentApplication
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer               getUserAssigned()          Returns the current record's "user_assigned" value
 * @method integer               getInvestmentappId()       Returns the current record's "investmentapp_id" value
 * @method string                getInstructions()          Returns the current record's "instructions" value
 * @method timestamp             getDuedate()               Returns the current record's "duedate" value
 * @method string                getWorkStatus()            Returns the current record's "work_status" value
 * @method InvestmentApplication getInvestmentApplication() Returns the current record's "InvestmentApplication" value
 * @method sfGuardUser           getSfGuardUser()           Returns the current record's "sfGuardUser" value
 * @method TaskAssignment        setUserAssigned()          Sets the current record's "user_assigned" value
 * @method TaskAssignment        setInvestmentappId()       Sets the current record's "investmentapp_id" value
 * @method TaskAssignment        setInstructions()          Sets the current record's "instructions" value
 * @method TaskAssignment        setDuedate()               Sets the current record's "duedate" value
 * @method TaskAssignment        setWorkStatus()            Sets the current record's "work_status" value
 * @method TaskAssignment        setInvestmentApplication() Sets the current record's "InvestmentApplication" value
 * @method TaskAssignment        setSfGuardUser()           Sets the current record's "sfGuardUser" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaskAssignment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('task_assignment');
        $this->hasColumn('user_assigned', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('investmentapp_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('instructions', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('duedate', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('work_status', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('InvestmentApplication', array(
             'local' => 'investmentapp_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_assigned',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable(array(
             'created:{ name' => 'created_by,type: string,onUpdate: CASCADE,onDelete: SET NULL,options: {notnull: true,default: None}}',
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}