<?php

/**
 * BaseEIAProjectSocialEconomic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $eiaproject_id
 * @property boolean $existing_settlements
 * @property string $existing_settlements_remark
 * @property integer $average_family_size
 * @property string $average_family_size_remark
 * @property boolean $livelihood_farming
 * @property boolean $livelihood_fishing
 * @property boolean $livelihood_vending
 * @property boolean $livelihood_others
 * @property string $livelihood_others_specify
 * @property boolean $local_organization
 * @property string $local_organization_description
 * @property boolean $social_infrastructures
 * @property boolean $social_health_centers
 * @property boolean $social_hospital
 * @property boolean $social_transportation
 * @property boolean $social_communication
 * @property boolean $social_churches
 * @property boolean $social_roads
 * @property boolean $social_others
 * @property string $social_others_specify
 * @property string $token
 * @property EIAProjectDetail $EIAProjectDetail
 * 
 * @method integer                  getEiaprojectId()                   Returns the current record's "eiaproject_id" value
 * @method boolean                  getExistingSettlements()            Returns the current record's "existing_settlements" value
 * @method string                   getExistingSettlementsRemark()      Returns the current record's "existing_settlements_remark" value
 * @method integer                  getAverageFamilySize()              Returns the current record's "average_family_size" value
 * @method string                   getAverageFamilySizeRemark()        Returns the current record's "average_family_size_remark" value
 * @method boolean                  getLivelihoodFarming()              Returns the current record's "livelihood_farming" value
 * @method boolean                  getLivelihoodFishing()              Returns the current record's "livelihood_fishing" value
 * @method boolean                  getLivelihoodVending()              Returns the current record's "livelihood_vending" value
 * @method boolean                  getLivelihoodOthers()               Returns the current record's "livelihood_others" value
 * @method string                   getLivelihoodOthersSpecify()        Returns the current record's "livelihood_others_specify" value
 * @method boolean                  getLocalOrganization()              Returns the current record's "local_organization" value
 * @method string                   getLocalOrganizationDescription()   Returns the current record's "local_organization_description" value
 * @method boolean                  getSocialInfrastructures()          Returns the current record's "social_infrastructures" value
 * @method boolean                  getSocialHealthCenters()            Returns the current record's "social_health_centers" value
 * @method boolean                  getSocialHospital()                 Returns the current record's "social_hospital" value
 * @method boolean                  getSocialTransportation()           Returns the current record's "social_transportation" value
 * @method boolean                  getSocialCommunication()            Returns the current record's "social_communication" value
 * @method boolean                  getSocialChurches()                 Returns the current record's "social_churches" value
 * @method boolean                  getSocialRoads()                    Returns the current record's "social_roads" value
 * @method boolean                  getSocialOthers()                   Returns the current record's "social_others" value
 * @method string                   getSocialOthersSpecify()            Returns the current record's "social_others_specify" value
 * @method string                   getToken()                          Returns the current record's "token" value
 * @method EIAProjectDetail         getEIAProjectDetail()               Returns the current record's "EIAProjectDetail" value
 * @method EIAProjectSocialEconomic setEiaprojectId()                   Sets the current record's "eiaproject_id" value
 * @method EIAProjectSocialEconomic setExistingSettlements()            Sets the current record's "existing_settlements" value
 * @method EIAProjectSocialEconomic setExistingSettlementsRemark()      Sets the current record's "existing_settlements_remark" value
 * @method EIAProjectSocialEconomic setAverageFamilySize()              Sets the current record's "average_family_size" value
 * @method EIAProjectSocialEconomic setAverageFamilySizeRemark()        Sets the current record's "average_family_size_remark" value
 * @method EIAProjectSocialEconomic setLivelihoodFarming()              Sets the current record's "livelihood_farming" value
 * @method EIAProjectSocialEconomic setLivelihoodFishing()              Sets the current record's "livelihood_fishing" value
 * @method EIAProjectSocialEconomic setLivelihoodVending()              Sets the current record's "livelihood_vending" value
 * @method EIAProjectSocialEconomic setLivelihoodOthers()               Sets the current record's "livelihood_others" value
 * @method EIAProjectSocialEconomic setLivelihoodOthersSpecify()        Sets the current record's "livelihood_others_specify" value
 * @method EIAProjectSocialEconomic setLocalOrganization()              Sets the current record's "local_organization" value
 * @method EIAProjectSocialEconomic setLocalOrganizationDescription()   Sets the current record's "local_organization_description" value
 * @method EIAProjectSocialEconomic setSocialInfrastructures()          Sets the current record's "social_infrastructures" value
 * @method EIAProjectSocialEconomic setSocialHealthCenters()            Sets the current record's "social_health_centers" value
 * @method EIAProjectSocialEconomic setSocialHospital()                 Sets the current record's "social_hospital" value
 * @method EIAProjectSocialEconomic setSocialTransportation()           Sets the current record's "social_transportation" value
 * @method EIAProjectSocialEconomic setSocialCommunication()            Sets the current record's "social_communication" value
 * @method EIAProjectSocialEconomic setSocialChurches()                 Sets the current record's "social_churches" value
 * @method EIAProjectSocialEconomic setSocialRoads()                    Sets the current record's "social_roads" value
 * @method EIAProjectSocialEconomic setSocialOthers()                   Sets the current record's "social_others" value
 * @method EIAProjectSocialEconomic setSocialOthersSpecify()            Sets the current record's "social_others_specify" value
 * @method EIAProjectSocialEconomic setToken()                          Sets the current record's "token" value
 * @method EIAProjectSocialEconomic setEIAProjectDetail()               Sets the current record's "EIAProjectDetail" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEIAProjectSocialEconomic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('e_i_a_project_social_economic');
        $this->hasColumn('eiaproject_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('existing_settlements', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('existing_settlements_remark', 'string', 800, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 800,
             ));
        $this->hasColumn('average_family_size', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('average_family_size_remark', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('livelihood_farming', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('livelihood_fishing', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('livelihood_vending', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('livelihood_others', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('livelihood_others_specify', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('local_organization', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('local_organization_description', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('social_infrastructures', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('social_health_centers', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('social_hospital', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('social_transportation', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('social_communication', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('social_churches', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('social_roads', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('social_others', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => false,
             ));
        $this->hasColumn('social_others_specify', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('EIAProjectDetail', array(
             'local' => 'eiaproject_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable(array(
             'created:{ name' => 'created_by,type: string,onUpdate: CASCADE,onDelete: SET NULL,options: {notnull: true,default: None}}',
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}