<?php

/**
 * BaseCertificationReport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $investment_certificates
 * @property integer $eia_certificates
 * @property integer $tax_exemptions
 * 
 * @method integer             getInvestmentCertificates()  Returns the current record's "investment_certificates" value
 * @method integer             getEiaCertificates()         Returns the current record's "eia_certificates" value
 * @method integer             getTaxExemptions()           Returns the current record's "tax_exemptions" value
 * @method CertificationReport setInvestmentCertificates()  Sets the current record's "investment_certificates" value
 * @method CertificationReport setEiaCertificates()         Sets the current record's "eia_certificates" value
 * @method CertificationReport setTaxExemptions()           Sets the current record's "tax_exemptions" value
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCertificationReport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('certification_report');
        $this->hasColumn('investment_certificates', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('eia_certificates', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('tax_exemptions', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable(array(
             'created:{ name' => 'created_by,type: string,onUpdate: CASCADE,onDelete: SET NULL,options: {notnull: true,default: None}}',
             'updated' => 
             array(
              'name' => 'updated_by',
              'type' => 'string',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}