# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: dashboard, action: index }
# Task assignment route
task:
 url: /tasks
 param: {module: taskAssign, action: index}
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
################### Application Security routing ################################
sf_guard_signin:
 url:   /login
 param: { module: sfGuardAuth, action: signin }
sf_guard_signout:
 url:   /logout
 param: { module: sfGuardAuth, action: signout }
sf_guard_forgot_password:
 url:   /password_recover
 param: { module: sfGuardAuth, action: password }
sf_guard_recover_password:
 url: /recover
 param: {module: sfGuardForgotPassword, action: index}
sf_guard_users:
 url:   /users
 param: { module: sfGuardUser, action: index }
sf_guard_user_groups:
 url:   /groups
 param: { module: sfGuardGroup, action: index }
sf_guard_user_permissions:
 url:   /permissions
 param: { module: sfGuardPermission, action: index }
sf_guard_register:
 url:   /register
 param: { module: sfGuardAuth, action: index }

##################ApplyPlugin route################# 
apply:
 url:  /apply
 param: { module: sfApply, action: apply }
reset:
 url: /reset
 param: { module: sfApply, action: reset }
resetRequest:
 url: /reset-request
 param: { module: sfApply, action: resetRequest }
validate:
 url: /confirm/:validate
 param: { module: sfApply, action: confirm }
settings:
 url: /settings
 param: { module: sfApply, action: settings }
sf_guard_password_reset:
 url: /reset-request
 param: { module: sfApply, action: resetRequest }