task_assignment_taskManagement:
  class: sfDoctrineRouteCollection
  options:
    model:                TaskAssignment
    module:               taskManagement
    prefix_path:          /taskManagement
    column:               id
    with_wildcard_routes: true

task_assignment:
  class: sfDoctrineRouteCollection
  options:
    model:                TaskAssignment
    module:               dataAdminJob
    prefix_path:          /dataAdminJob
    column:               id
    with_wildcard_routes: true
####Route for message module for frontend
my_inbox:
 url: /inbox
 param: { module: messages, action: index}

user_tasks:
 url: /mytasks
 param: {module: taskManagement, action: tasks }
start_work:
 url: /start
 param: {module: dashboard, action:start}
make_report: #Route for creating a new Project Summary Report
 url: /make/report
 param: {module: projectSummary, action: new}
investment_cert_task:
 url: /certificate/taskAssign
 param: { module: InvestmentCertTaskAssignment, action: index }
information_portlets:
 url: /information/portlets
 param: { module: portlets, action: index }
# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: dashboard, action: index }
# Task assignment route
task:
 url: /tasks
 param: {module: taskAssign, action: index}
# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
 # param: { action: index }
investment_certificates:
 url: /certificates
 param: {module: investmentcertificates, action: index }
default:
  url:   /:module/:action/*
################### Application Security routing ################################
sf_guard_signin:
 url:   /login
 param: { module: sfGuardAuth, action: signin }
sf_guard_signout:
 url:   /logout
 param: { module: sfGuardAuth, action: signout }
sf_guard_users:
 url:   /users
 param: { module: sfGuardUser, action: index }
sf_guard_user_groups:
 url:   /groups
 param: { module: sfGuardGroup, action: index }
sf_guard_user_permissions:
 url:   /permissions
 param: { module: sfGuardPermission, action: index }

##################ApplyPlugin route################# 
apply:
 url:  /apply
 param: { module: sfApply, action: apply }
reset:
 url: /reset
 param: { module: sfApply, action: reset }
resetRequest:
 url: /reset-request
 param: { module: sfApply, action: resetRequest }
validate:
 url: /confirm/:validate
 param: { module: sfApply, action: confirm }
settings:
 url: /settings
 param: { module: sfApply, action: settings }
sf_guard_password_reset:
 url: /reset-request
 param: { module: sfApply, action: resetRequest }