<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/11 14:44:21

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rdbeportal',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
