<?php

/**
 * BusinessPlan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BusinessPlan extends BaseBusinessPlan
{
    public function save(Doctrine_Connection $conn = null)
	  {
	   $conn = $conn ? $conn : $this->getTable()->getConnection();
	   $conn->beginTransaction();
			  try
			  {
				  //we will override this method. we update the application status of this investor. for now we use coded status
				  //later we will try and find a better solution
				  $businessStatus = new BusinessApplicationStatus();
				  //we retrieve the neccessary values from this model
				  $businessId = $this->getInvestmentId();
				  //hard coded status and comments
				  $status = "submitted" ;
				  $comments = "Documents Submitted Successfuly. Awaiting RDB admin to assign your application to a Staff";
				  $percentage = 10 ;
				  //pass values
				  $businessStatus->business_id = $businessId ;
				  $businessStatus->application_status =$status;
				  $businessStatus->comment = $comments ;
				  $businessStatus->percentage = $percentage ;
				  //save
				  $businessStatus->save();
				  
				  ///
				  $ret = parent::save($conn);
					$conn->commit();
					return $ret ;
				
			  }
			  catch(Exception $e)
			  {
			  $conn->rollBack();
			  throw $e;
			  }
	  }
}