<?php

/**
 * BusinessApplicationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BusinessApplicationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BusinessApplicationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BusinessApplicationStatus');
    }
}