<?php

/**
 * BusinessPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BusinessPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BusinessPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BusinessPlan');
    }
}