<?php

/**
 * BusinessApplicationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BusinessApplicationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BusinessApplicationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BusinessApplicationStatus');
    }
	/*
	These methods are used to manually update the status of application. Seems sysmfony has no good way to implement a workflow
	hence we have to work with functions and look for a better solution later.
	*/
	// 1.  update the status of the user application after the Documents Have Been Assigned to RDB Staff
	public function updateStatus($id,$value)
	{
	 
	 //query
	 $q = Doctrine_Query::create()
	 ->UPDATE('BusinessApplicationStatus')
	 ->SET('application_status', '?' , $value)
	 ->WHERE('business_id = ?', $id);
	 $q->execute();
	}
	//update the comment
	public function updateComment($id,$value )
	{
	 
	 //query
	 $q = Doctrine_Query::create()
	 ->UPDATE('BusinessApplicationStatus')
	 ->SET('comment', '?' , $value)
	 ->WHERE('business_id = ?', $id);
	 $q->execute();
	}
	public function updateValue($id,$value)
	{
	 $q = Doctrine_Query::create()
	 ->UPDATE('BusinessApplicationStatus')
	 ->SET('percentage', '?' , $value)
	 ->WHERE('business_id = ?', $id);
	 $q->execute();
	}
	// End Updating Functions
	//check if a certain business application for investment certificate has been rejected
	public function checkStatus($investment_id)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("select application_status from business_application_status where business_id = '$investment_id' ");
	 //
	 $status = null ;
	 //
	 foreach($query as $q)
	 {
	   $status = $q['application_status'];
	 }
	 //
	 return $status;
	}
	
}