<?php

/**
 * CertificationReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CertificationReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CertificationReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CertificationReport');
    }
	
	
}