<?php

/**
 * costsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class costsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object costsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('costs');
    }
}