<?php

/**
 * EIAAssessmentDecisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAAssessmentDecisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAAssessmentDecisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAAssessmentDecision');
    }
	
	public static $decisions=array( 
		'accept' => 'Accept',
		'decline' => 'Decline',
	);
	
	public function getDecisions()
	{
		return self::$decisions;
	}
}