<?php

/**
 * EIAAssessmentDecisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAAssessmentDecisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAAssessmentDecisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAAssessmentDecision');
    }
	
	public static $decisions=array( 
		'accept' => 'Accept',
		'decline' => 'Decline',
	);
	
	public function getDecisions()
	{
		return self::$decisions;
	}
	
	public static $stages = array(
		'site-visit' => 'Site visit',
		'impact-level' => 'Impact level',
		'tor' => 'Terms of Reference',
		'eir' => 'EI Report',
		'eia-cert' => 'EIA Certificate',
	);
	
	public function getStages()
	{
		return self::$stages;
	}
	
	public function getAssessmentId($taskAssignment_id)
	{
		$q= $this->createQuery('a')
			->select('a.id')
			->where('a.taskassignment_id = ?',$taskAssignment_id)
			->orderBy('a.id DESC')
			->limit(1);
		return $q->fetchArray();
	}
	
	public function getAssessment($taskAssignment_id,$eia_stage)
	{
		$q=$this->createQuery('a')
			->select('a.*')
			->where('a.taskassignment_id = ?',$taskAssignment_id)
			->andWhere('a.eia_stage = ?',$eia_stage);
		return $q->fetchArray();
	}
			
}