<?php

/**
 * EIACertificateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIACertificateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIACertificateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIACertificate');
    }
	public function getLastRow()
	{
		$q=$this->createQuery('c')
			->select('c.*')
			->orderBy('c.serial_number DESC');
		return $q->fetchArray();
	}
	///////a report function
	public function calculateCertificatesIssued()
	{
	 $certs = 0;
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("select count(serial_number) as total from e_i_a_certificate");
	 foreach($query  as $q)
	 {
	  $certs = $q['total'];
	 }
	 //
	 return $certs;
	}
}