<?php

/**
 * EIAProjectDeveloperTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectDeveloperTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectDeveloperTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectDeveloper');
    }
	
	public static $socials= array( 
		'twitter' => "Twitter",
		'facebook' => "Facebook",
		'google+' => "Google-plus",
		'linkedin' => "Linkedin",
		);
	public function getSocials()
	{
		return self::$socials;
	}
	///method to search for a certain id
	public function queryForId($project_id)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT id, token from  e_i_a_project_developer WHERE eiaproject_id = '$project_id' limit 1 ");
	 ///
	 return $query;
	}
    ///
    //method to get token  and id from this table given an id of the record
	public function getProjectDetailTokenAndId($eiaproject_id)
	{
	 //print "eiaproject_id is ".$eiaproject_id ;exit;
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT token, id FROM e_i_a_project_developer WHERE eiaproject_id = '$eiaproject_id' limit 1");
	 //
	 
	 return $query;
	}	
		
}