<?php

/**
 * EIAProjectDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectDescription');
    }
}