<?php

/**
 * EIAProjectAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EIAProjectAttachment extends BaseEIAProjectAttachment
{
   public function save(Doctrine_Connection $conn = null)
  {
   $conn = $conn ? $conn : $this->getTable()->getConnection();
   $conn->beginTransaction();
		  try
		  {
			  
			  ///
		  if (!$this->getToken() && !$this->getProjectReferenceNumber())
		  {
			$this->setToken(sha1(date().rand(11111, 99999)));
			//get the incremental number and set it
			$number = Doctrine_Core::getTable('EIAProjectDetail')->createIncrementalReferenceNumber();
			$this->setProjectReferenceNumber($number);
			
		  }
		  //we want also to set an incremental reference number for each and every project
		  
				//Save status of application
				$status = new EIApplicationStatus();
				$status->eiaproject_id=$this->getEiaprojectId();
				$status->application_status='submitted';
				$status->comments='Your Application has been submitted.Awaiting RDB admin to assign your application to a Staff';
				$status->percentage=10;
				$status->save();
				
		 	 
			  $ret = parent::save($conn);
				$conn->commit();
				return $ret ;
			
		  }
		  catch(Exception $e)
		  {
		  $conn->rollBack();
		  throw $e;
		  }
  }
}