<?php

/**
 * EIAProjectSocialEconomicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectSocialEconomicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectSocialEconomicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectSocialEconomic');
    }
}