<?php

/**
 * EIAProjectSocialEconomicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectSocialEconomicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectSocialEconomicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectSocialEconomic');
    }
	//
	///method to search for a certain id
	public function queryForId($project_id)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT id, token from e_i_a_project_social_economic WHERE eiaproject_id = '$project_id' limit 1 ");
	 ///
	 return $query;
	}
}