<?php

/**
 * EIApplicationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIApplicationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIApplicationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIApplicationStatus');
    }
	
	public function updateCompanyId($companyId, $id)
	{
		$q = Doctrine_Query::create()
			->UPDATE('EIApplicationStatus')
			->SET('company_id', '?', $companyId)
			->WHERE('created_by = ?', $id); 
		
		return $q->execute();
	}
	
	public function updateApplicationStatus($appStatus)
	{
		$q = Doctrine_Query::create()
			->UPDATE('EIApplicationStatus')
			->SET('application_status', '?', $appStatus);
			->WHERE('created_by = ?', $id);	
		return $q->execute();
	}
	
	public function updateComment($comment)
	{
		$q = Doctrine_Query::create()
			->UPDATE('EIApplicationStatus')
			->SET('comments', '?',$comment);
			->WHERE('created_by = ?', $id);
			
		return $q->execute();
	}
	

}
		