<?php

/**
 * EIAProjectDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectDetail');
    }
}