<?php

/**
 * EIApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIApplicationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIApplicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIApplication');
    }
}