<?php

/**
 * EIApplicationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIApplicationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIApplicationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIApplicationStatus');
    }
	
	public function getUserStatus()
	{
		$userId = sfContext::getInstance()->getUser()->getGuardUser()->getId();
		$query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT e_i_a_project_detail.project_title,e_i_a_project_detail.id,e_i_application_status.application_status,e_i_application_status.comments,e_i_application_status.percentage FROM e_i_application_status LEFT JOIN e_i_a_project_detail ON e_i_a_project_detail.id = e_i_application_status.eiaproject_id WHERE e_i_a_project_detail.created_by = '$userId' ");
		 
		return $query;
	}	
	public function getApplicationStatus($status)
	{
		$query=Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT e_i_application_status.id,e_i_a_project_detail.project_reference_number,e_i_a_project_detail.project_title,e_i_a_project_developer.developer_name FROM e_i_application_status LEFT JOIN e_i_a_project_detail ON e_i_a_project_detail.id = e_i_application_status.eiaproject_id LEFT JOIN e_i_a_project_developer ON e_i_a_project_developer.eiaproject_id = e_i_a_project_detail.id WHERE e_i_application_status.application_status = '$status' ORDER BY e_i_a_project_detail.project_reference_number DESC ");
		
		return $query;
	}
	public function updateApplicationStatus($appStatus,$id)
	{
		$q = Doctrine_Query::create()
			->UPDATE('EIApplicationStatus')
			->SET('application_status', '?', $appStatus)
			->WHERE('company_id = ?', $id);	
		return $q->execute();
	}
	
	public function updateComment($comment,$id)
	{
		$q = Doctrine_Query::create()
			->UPDATE('EIApplicationStatus')
			->SET('comments', '?',$comment)
			->WHERE('company_id = ?', $id);
			
		return $q->execute();
	}
	
	public function updatePercentage($percent,$id)
	{
		$q = Doctrine_Query::create()
			->UPDATE('EIApplicationStatus')
			->SET('percentage', '?',$percent)
			->WHERE('company_id = ?', $id);
			
		return $q->execute();
	}
}
		