<?php

/**
 * EIAProjectImpactMeasuresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectImpactMeasuresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectImpactMeasuresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectImpactMeasures');
    }
}