<?php

/**
 * EIApplicationCertificatePermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIApplicationCertificatePermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIApplicationCertificatePermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIApplicationCertificatePermission');
    }
}