<?php

/**
 * EIAProjectSurroundingSpeciesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectSurroundingSpeciesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectSurroundingSpeciesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectSurroundingSpecies');
    }
}