<?php

/**
 * EIAProjectSurroundingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectSurroundingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectSurroundingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectSurrounding');
    }
	
	public static $units= array(
		'meters' =>'m',
		'kilometers' => 'Km'
	);
	
	public function getUnits()
	{
		return self::$units;
	}

	public function getProjectSurroundingId()
	{
		$userId = sfContext::getInstance()->getUser()->getGuardUser()->getId(); // get the id of the user logged
		$query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT e_i_a_project_surrounding.id FROM e_i_a_project_surrounding WHERE created_by = '$userId' order by e_i_a_project_surrounding.id desc limit 1 ");
		
		foreach($query as $q){
			$id=$q['id'];
		}
		
		return $id;
	}
	////
	///method to search for a certain id
	public function queryForId($project_id)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT id, token from  e_i_a_project_surrounding WHERE eiaproject_id = '$project_id' limit 1 ");
	 ///
	 return $query;
	}
	  ///
    //method to get token  and id from this table given an id of the record
	public function getProjectSurroundingTokenAndId($eiaproject_id)
	{
	 //print "eiaproject_id is ".$eiaproject_id ;exit;
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT token, id FROM e_i_a_project_surrounding WHERE eiaproject_id = '$eiaproject_id' limit 1");
	 //
	 
	 return $query;
	}
	public function updateResubmit($status,$id)
	{
		$q=Doctrine_Query::create()
		->update('EIAProjectSurrounding s')
		->set('s.resubmit','?',$status)
		->where('s.eiaproject_id = ?',$id);
		$q->execute();
	}
}