<?php

/**
 * EIAProjectBriefDecisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectBriefDecisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectBriefDecisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectBriefDecision');
    }
	
	public static $actionResubmit=array(
		'heading' => 'Resubmission',
		'body' => 'Please specify to the applicant why you are requesting for a resubmission'
	);
	
	public static $actionReject=array(
		'heading' => 'Rejection',
		'body' => 'Please specify to the applicant why you are rejecting the application'
	);
	
	public function getActionResubmit()
	{
		return self::$actionResubmit;
	}
	
	public function getActionReject()
	{
		return self::$actionReject;
	}
	public static $forms=array(
		'all' => 'ALL FORMS',
		'EIAProjectDetail' => 'Project Detail Form',
		'EIAProjectDeveloper' => 'Project Developer Form',
		'EIAProjectDescription' => 'Project Description Form',
		'EIAProjectSurrounding' => 'Project Surrounding Form',
		'EIAProjectSurroundingSpecies' => 'Project Surrounding Species Form',
		'EIAProjectSocialEconomic' => 'Project Social Economic Form',
		'EIAProjectImpactMeasures' => 'Project Impact Measures Form',
		'EIAProjectOperationPhase' => 'Project Operation Phase Form',
		'EIAProjectAttachment' => 'Project Attachment Form' 
	);
	public function getForms()
	{
		return self::$forms;
	}
}