<?php

/**
 * EIAProjectDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectDescription');
    }
    static public $natures = array(
				'Agriculture forestry and fishing' => 'Agriculture, forestry and fishing',
				'Mining and quarrying'=> 'Mining and quarrying ',
				'Manufacturing' => 'Manufacturing',
				'Electricity, gas, steam and air conditioning supply' => 'Electricity, gas, steam and air conditioning supply',
				'Water supply; sewerage, waste management and remediation activities' => 'Water supply; sewerage, waste management and remediation activities',
				'Construction' => 'Construction',
				'Wholesale and retail trade; repair of motor vehicles and motorcycles' => 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
				'Transportation and storage' => 'Transportation and storage',
				'Accommodation and food service activities'=> 'Accommodation and food service activities',
				'Information and communication'=> 'Information and communication',
				'Financial and insurance activities' => 'Financial and insurance activities',
				'Real estate activities' => 'Real estate activities',
				'Professional, scientific and technical activities' => 'Professional, scientific and technical activities ',
				'Administrative and support service activities' => 'Administrative and support service activities',
				'Public administration and defence; compulsory social security' => 'Public administration and defence; compulsory social security',
				'Education' => 'Education',
				'Human health and social work activities' => 'Human health and social work activities',
				'Arts, entertainment and recreation' => 'Arts, entertainment and recreation',
				'Other service activities' => 'Other service activities',
				'Activities of households as employers; undifferentiated goods- and  
services-producing activities of households for own use' => 'Activities of households as employers; undifferentiated goods- and  
services-producing activities of households for own use',
				'Activities of extraterritorial organizations and bodies' => 'Activities of extraterritorial organizations and bodies',
				
			  );
	public function getNatures()
	{
	 return self::$natures;
	}
	///
	static public $possibilities = array('true' => 'Yes', 'false' => 'No');
	public function getQuestionValues()
	{
	 return self::$possibilities;
	}
	///
	///method to search for a certain id
	public function queryForId($project_id)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT id, token from  e_i_a_project_description WHERE eiaproject_id = '$project_id' limit 1 ");
	 ///
	 return $query;
	}
	//method to get token  and id from this table given an id of the record
	public function getProjectDetailTokenAndId($eiaproject_id)
	{
	 //print "eiaproject_id is ".$eiaproject_id ;exit;
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT token, id FROM e_i_a_project_description WHERE eiaproject_id 	 = '$eiaproject_id' limit 1");
	 //
	 
	 return $query;
	}
}