<?php

/**
 * EIAProjectImpactPassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAProjectImpactPassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAProjectImpactPassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAProjectImpactPass');
    }
}