<?php

/**
 * EIAReportsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIAReportsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIAReportsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIAReports');
    }
	
	public static $modules = array( 
		'eia' => 'EIA',
		'tor' => 'TOR',
	);
	
	public function getModules()
	{
		return self::$modules;
	}
}