<?php

/**
 * EIASiteVisitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIASiteVisitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIASiteVisitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIASiteVisit');
    }
	
	public static $reschedule= array(
		'info' => 'Select the new date for the site visit',
		'header' => 'Reschedule',
	);
	public static $schedule= array(
		'header' => 'Schedule',
		'info' => 'Select the day for the site visit.The request will be approved by the supervisor',
	);
	public function getReschedule()
	{
		return self::$reschedule;
	}
	public function getSchedule()
	{
		return self::$schedule;
	}
	
	public function getSiteVisitReport()
	{
		$userId = sfContext::getInstance()->getUser()->getGuardUser()->getId(); 
		$q=$this->createQuery('s')
			->select('s.id,s.site_visit,d.project_reference_number,d.project_title')
			->leftJoin('s.EIAProjectDetail d')
			->where('s.created_by = ?',$userId )
			->andWhere('s.site_visit <= ?',date('Y-m-d',time()))
			->andWhere('s.visited = ?',False)
			->orderBy('s.site_visit DESC');
		return $q->fetchArray();
	}
	public function getSiteVisit()
	{
		$userId = sfContext::getInstance()->getUser()->getGuardUser()->getId(); 
		$q= $this->createQuery('s')
			->select('s.eiaproject_id,s.site_visit,d.project_title')
			->leftJoin('s.EIAProjectDetail d')
			->where('s.created_by = ?',$userId )
			->andWhere('s.site_visit >= ?',date('Y-m-d',time()))
			->orderBy('s.site_visit ASC');
			
		return $q->fetchArray();
	}
}