<?php

/**
 * EIASiteVisitReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIASiteVisitReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIASiteVisitReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIASiteVisitReport');
    }
}