<?php

/**
 * EIATorStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIATorStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIATorStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIATorStatus');
    }
}