<?php

/**
 * EICommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EICommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EICommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIComments');
    }
}