<?php

/**
 * EIReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIReport');
    }
	//get eireports submitted by users
	public function getEIReports()
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT * from e_i_report");
	 //
	 return $query;
	}
	//updates status after a user resubmits successfuly
	public function updateStatus($project_id)
	{
	 $value = "awaitinganalysis";
	 //
      $q = Doctrine_Query::create()
	 ->UPDATE('EIReport')
	 ->SET('status', '?' , $value)
	 ->WHERE('eiaproject_id  = ?', $project_id);
	 $q->execute();
	}
}