<?php

/**
 * EIReportResubmissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIReportResubmissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIReportResubmissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIReportResubmission');
    }
	//check if this user EIReport submission requires resubmission
	public function checkResubmissionStatus($user_id)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("select eiaproject_id,status  from e_i_report where status = 'awaitingresubmission' and created_by = '$user_id' ");
	 return $query;
	}
}