<?php

/**
 * EIReportResubmissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIReportResubmissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIReportResubmissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIReportResubmission');
    }
	//check if this user EIReport submission requires resubmission
	public function checkResubmissionStatus($user_id)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("select id, status from e_i_report where status = 'awaitingresubmission' ");
	 return $query;
	}
	//select document from EIReportResubmission with status awaitingresubmission
	public function getCommentsDocument($project_id)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("select commets_doc from e_i_report_resubmission where status = 'awaitingresubmission'  and eiaproject_id = '$project_id' limit 1");
	 return $query;
	}
	//updates status after a user resubmits successfuly
	public function updateStatus($project_id)
	{
	 $value = "awaitinganalysis";
	 //
      $q = Doctrine_Query::create()
	 ->UPDATE('EIReportResubmission')
	 ->SET('status', '?' , $value)
	 ->WHERE('eiaproject_id  = ?', $project_id);
	 $q->execute();
	}
}