<?php

/**
 * EIReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EIReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EIReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EIReport');
    }
}