<?php

/**
 * EITaskAssignment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EITaskAssignment extends BaseEITaskAssignment
{
	public function save(Doctrine_Connection $conn = null)
	  {
	   $conn = $conn ? $conn : $this->getTable()->getConnection();
	   $conn->beginTransaction();
			  try
			  {
				if(!$this->getToken())
				{
					$this->setToken(sha1(date().rand(11111,99999)));
				}
				$statusId=Doctrine_Core::getTable('EIApplicationStatus')->findByEiaprojectId($this->getEiaprojectId());
				$status=Doctrine_Core::getTable('EIApplicationStatus')->find(array($statusId[0]['id']));
				$status->setApplicationStatus('assigned');
				$status->setComments('Your Document has been assigned to a RDB Data Admin Staff');
				$status->setPercentage(30);
				$status->save();
				  $ret = parent::save($conn);
					$conn->commit();
				//Doctrine_Core::getTable('EIApplicationStatus')->updateApplicationStatus("assigned",	$this->getCompanyId());
				//Doctrine_Core::getTable('EIApplicationStatus')->updateComment("Your Document has been assigned to a RDB Data Admin Staff",	$this->getCompanyId());
				//Doctrine_Core::getTable('EIApplicationStatus')->updatePercentage("30",	$this->getCompanyId());
					return $ret ;
				
			  }
			  catch(Exception $e)
			  {
			  $conn->rollBack();
			  throw $e;
			  }
	  }


}