<?php

/**
 * InvestmentCertificateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvestmentCertificateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvestmentCertificateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvestmentCertificate');
    }
	//this method returns the last row serial number. 
	public function getLastRow()
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc('
	 SELECT id,investment_certificate.serial_number FROM investment_certificate ORDER BY investment_certificate.id DESC LIMIT 1
	 ');
	 return $query;
	}
	/*This method will return details of applicant using the business_id submitted*/
	public function getApplicantDetails($business_id)
	{
	  $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
	  "SELECT  investment_certificate.created_at,investment_certificate.serial_number,
		 investment_application.name,investment_application.currency_type , investment_application.name,investment_application.representative_name,project_summary.employment_created,
		 project_summary.business_sector,project_summary.planned_investment, sf_guard_user.first_name,sf_guard_user.last_name
		 FROM investment_certificate LEFT JOIN  investment_application ON investment_certificate.business_id 
		LEFT JOIN project_summary ON investment_certificate.business_id = project_summary.investment_id 
		LEFT JOIN sf_guard_user ON sf_guard_user.id = project_summary.created_by WHERE investment_application.id = '$business_id' "
	  );
	  return $query;
	}
	public function getApplicantCertificateDetails($id)
	{
	  $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc(
	  "SELECT  investment_certificate.created_at,investment_certificate.serial_number,
		 investment_application.name, investment_application.name,investment_application.representative_name,project_summary.employment_created,
		 project_summary.business_sector,project_summary.planned_investment, sf_guard_user.first_name,sf_guard_user.last_name
		 FROM investment_certificate LEFT JOIN  investment_application ON investment_certificate.business_id 
		LEFT JOIN project_summary ON investment_certificate.business_id = project_summary.investment_id 
		LEFT JOIN sf_guard_user ON sf_guard_user.id = project_summary.created_by WHERE investment_application.id = '$id' "
	  );
	  return $query;
	}
	/*
	Method to search for a business given an id
	*/
	public function searchBusiness($id)
	{
	  $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
	  SELECT investment_certificate.id 	FROM investment_certificate WHERE investment_certificate.business_id = '$id'
	  ");
	  return $query;
	}
	/*
	 Return a list of Certificates and business details issued by the current logged in user. i.e. data administrator
	*/
	public function getAdminIssuedCerts($username)
	{
	  $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("
		SELECT investment_certificate.serial_number, investment_application.name,
		investment_application.location ,investment_application.name,
		investment_certificate.created_at		
		FROM investment_certificate LEFT JOIN investment_application ON investment_certificate.business_id =
		investment_application.id  WHERE investment_certificate.updated_by = '$username'  
	  ");
	  return $query;
	}
	//get the investor email address using passed id
	public function getInvestorEmail($id)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT investment_application.updated_by,
	 sf_guard_user.email_address
	 from investment_application left join sf_guard_user on investment_application.created_by = sf_guard_user.id 
	 where investment_application.id = '$id'
	 ");
	 return $query;
	}
	//we show user notification for application of investment certificate.
	//reporting method on all investment certificates successfully issued.
	public function getAllIssuedCertificates()
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT investment_application.id, investment_application.name AS company, investment_application.office_telephone AS contact, investment_application.business_sector AS description, project_summary.business_sector AS sector, investment_certificate.serial_number, project_summary.planned_investment AS investment,project_summary.employment_created as jobs
		FROM investment_application
		LEFT JOIN investment_certificate ON investment_application.id = investment_certificate.business_id
		LEFT JOIN project_summary ON investment_application.id = project_summary.investment_id");
	 return $query;
	}
	  
}