<?php

/**
 * InvestmentCertificateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvestmentCertificateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvestmentCertificateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvestmentCertificate');
    }
}