<?php

/**
 * InvestmentApplication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class InvestmentApplication extends BaseInvestmentApplication
{
 //my custom toString method
  public function __toString()
  {
    return sprintf('%s',$this->getName());
  }

   // We want to Override this method and check if this business is registered. Simple Simulation
   //If not we display appropriate message informing the user of the error
  public function save(Doctrine_Connection $conn = null)
  {
   $conn = $conn ? $conn : $this->getTable()->getConnection();
   $conn->beginTransaction();
		  try
		  {
			  ///
			  $ret = parent::save($conn);
			  $this->updateLuceneIndex();
			  $conn->commit();
			  return $ret ;
			
		  }
		  catch(Exception $e)
		  {
		  $conn->rollBack();
		  throw $e;
		  }
  }
  //This function will do the job, check if submitted Business name and Registration number exists
  public function validateBusiness($name, $regno)
  {
   $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT * FROM business_registration WHERE business_name = '$name'
   AND business_regno = '$regno'");
  // print_r($query); exit;
   return $query;
  }
  //method to update index every time an application is created
  public function updateLuceneIndex()
  {
   $index = InvestmentApplicationTable::getLuceneIndex();
   //remove existing entries
   foreach($index->find('pk:'.$this->getId()) as $hit)
   {
     $index->delete($hit->id);
   }
   //
   $doc = new Zend_Search_Lucene_Document();
   //store application primary key to identify it in the search results
   $doc->addField(Zend_Search_Lucene_Field::Keyword('pk',$this->getId()));
   //index investor application fields
   $doc->addField(Zend_Search_Lucene_Field::UnStored('name',$this->getName(),'utf-8'));
   $doc->addField(Zend_Search_Lucene_Field::UnStored('location',$this->getLocation(),'utf-8'));
   $doc->addField(Zend_Search_Lucene_Field::UnStored('registration_number',$this->getRegistrationNumber(),'utf-8'));
   $doc->addField(Zend_Search_Lucene_Field::UnStored('sector',$this->getSector(),'utf-8'));
   $doc->addField(Zend_Search_Lucene_Field::UnStored('district',$this->getDistrict(),'utf-8'));
   $doc->addField(Zend_Search_Lucene_Field::UnStored('city_province',$this->getCityProvince(),'utf-8'));
   ///add application to index
   $index->addDocument($doc);
   $index->commit();
   
  }
  //override default delete method to remove index of deleted jobs
  public function delete(Doctrine_Connection $conn = null)
  {
   $index = InvestmentApplication::getLuceneIndex();
   //
   foreach($index->find('pk:'.$this->getId()) as $hit)
   {
    $index->delete($hit->id);
   }
   //
   return parent::delete($conn);
  }
  
}