<?php

/**
 * InvestmentRequestsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvestmentRequestsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InvestmentRequestsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InvestmentRequests');
    }
	//we set default fields for request_types
	static public $request_types= array(
    'issue_certificate' => 'Issue Certificate',
    'decline_application' => 'Decline Application',
    'accept_application' => 'Accept Application',
  );
  //
  //we set default fields for status
	static public $status= array(
    'accept' => 'Accept',
    'decline' => 'Decline',
  );
  //
  public function getStatus()
  {
   return self::$status ;
  }
  ///
  public function getRequestTypes()
  {
   return self::$request_types ;
  }
  //we create a function that querys for permission for declining an applicant application for issuance of investment certificate.
  //we pass business registration number here. this method will query for passed regno and search for status = accept, 
  //request_type = decline_application for the current logged in user
  public function queryPermission($regno, $username)
  {
   // print $username; exit;
    $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT request_type from investment_requests WHERE 
	investment_requests.business_registration = '$regno' and investment_requests.requestor = '$username' and status = 'accept'
    and request_type = 'decline_application'
	");
	return $query;
  }
}