<?php

/**
 * PlannedperformanceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlannedperformanceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlannedperformanceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Plannedperformance');
    }
}