<?php

/**
 * ProjectImpactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProjectImpactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProjectImpactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProjectImpact');
    }
}