<?php

/**
 * PublicHearingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicHearingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicHearingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PublicHearing');
    }
}