<?php

/**
 * SiteVisitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SiteVisitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SiteVisitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SiteVisit');
    }
}