<?php

/**
 * StructurefinancialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StructurefinancialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StructurefinancialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Structurefinancial');
    }
}