<?php

/**
 * TaxExemptionItemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxExemptionItemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxExemptionItemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxExemptionItems');
    }
}