<?php

/**
 * TaxExemptionDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxExemptionDetailsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxExemptionDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxExemptionDetails');
    }
	//we write a method that retrieves data that needs processing for tax exemption incentive
	public function getAllTaxExemptionRequests($status)
	{
	 $query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT * FROM tax_exemption_details WHERE status = '$status' ");
	 //
	 return $query;
	}
}