<?php

/**
 * TorDecisions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rdbeportal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TorDecisions extends BaseTorDecisions
{
	public function save(Doctrine_Connection $conn = null)
	{
	   $conn = $conn ? $conn : $this->getTable()->getConnection();
	   $conn->beginTransaction();
			try
			{
				  
				  
				  $ret = parent::save($conn);
					$conn->commit();
					Doctrine_Core::getTable('TorStatus')->updateStatus('Processed','TOR has been processed',$this->getTorId());
					return $ret ;
				
			}
			catch(Exception $e)
			{
			$conn->rollBack();
			throw $e;
			}
	}
}