<?php

/**
 * TorStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TorStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TorStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TorStatus');
    }
	
	static public $decisions = array(
		'Reject',
		'Approve',
	);
	
	public function getDecisions()
	{
		return self::$decisions;
	}
}