<?php

/**
 * TorStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TorStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TorStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TorStatus');
    }
	
	public function updateStatus($status, $comment,$id)
	{
		$q = Doctrine_Query::create()
			->UPDATE('TorStatus')
			->SET('status', '?',$status)
			->SET('comments', '?', $comment)
			->WHERE('tor_id = ?', $id);
			
		return $q->execute();
	}
	
	public function getStatus()
	{
		$userid = sfContext::getInstance()->getUser()->getGuardUser()->getId(); // get the username of the user logged
		$query = Doctrine_Manager::getInstance()->getCurrentConnection()->fetchAssoc("SELECT * FROM tor_status WHERE created_by = '$userid' 
		");
		return $query;
	}
}