<?php

/**
 * TorSubmitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TorSubmitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TorSubmitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TorSubmit');
    }
}