# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: investmentapp, action: index }
localized_homepage:
  url:   /:sf_culture/
  param: { module: investmentapp, action: index }
  requirements:
   sf_culture: (?:en|fr|rw)
change_language:
  url:   /change_language
  param: { module: language, action: changeLanguage }
### Route for eireport submission
eireport:
 url: /report/submission
 param: {module: eireport, action: new}
####Route for message module for frontend
my_inbox:
 url: /:sf_culture/inbox
 param: { module: messages, action: index}
####Route for my certificates
my_certificate:
 url: /:sf_culture/issued/certificates
 param: {module: investmentcertificates, action: index }
##
investmentapp:
 class: sfDoctrineRouteCollection
 options: {model: InvestmentApplication}
 prefix_path: /:sf_culture
investmentapp_edit:
 url: /:sf_culture/investmentapp/:id/
 class: sfDoctrineRoute
 options: {model: InvestmentApplication, type: object}
 param: {module: investmentapp, action: edit}
 requirements:
  id: \d+
businessplan:
 class: sfDoctrineRouteCollection
 options: {model: BusinessPlan}
 preifx_path: /:sf_culture
businessplan_edit:
 url: /:sf_culture/businessplan/:id/:token
 class: sfDoctrineRoute
 options: {model: BusinessPlan, type: object}
 param: {module: businessplan, action: edit}
 requirements:
  id: \d+
  token: \w+
businessplan_loading:
 url: /:sf_culture/businessplan/loading/
 class: sfDoctrineRoute
 options: {model: BusinessPlan, type: object}
 param: {module: businessplan, action: loading}
# generic rules
# please, remove them by adding more specific rules
## Rules for EIA
project_detail:
 url: start/project/detail
 param: {module: projectDetail, action: new}
project_developer:
 url: project/developer
 param: {module: eiaProjectDeveloper, action: new}
project_description:
 url: /description
 param: {module: projectDescription, action: new}
project_surrounding:
 url: /project/surrounding
 param: {module: eiaProjectSurrounding, action: new }
project_surrounding_species:
 url: project/sorrounding/species
 param: {module: projectSorroundingSpecies, action: new}
project_social_economic:
 url: project/social/economic/environment
 param: {module: projectSocialEconomic, action: new}
project_impact_measures:
 url: project/impact/measures
 param: {module: projectImpactMeasures, action: new}
project_operation_phase:
 url: project/operation/phase
 param: {module: projectOperationPhase, action: new}
project_attachments:
 url: project/attachments
 param: {module: projectAttachment, action: new}

#default_index:
#  url:   /:module
#  param: { action: index }

default:
  url:   /:module/:action/*
##Errors will complete on this later
errors:
 url: /error
 param: {module: errors, action: index}

################### Application Security routing ################################
sf_guard_forgot_password:
 url:   /password_recover
 param: { module: sfGuardAuth, action: password }
sf_guard_recover_password:
 url: /recover
 param: {module: sfGuardForgotPassword, action: index}
sf_guard_users:
 url:   /users
 param: { module: sfGuardUser, action: index }
sf_guard_user_groups:
 url:   /groups
 param: { module: sfGuardGroup, action: index }
sf_guard_user_permissions:
 url:   /permissions
 param: { module: sfGuardPermission, action: index }
sf_guard_register:
 url:   /register
 param: { module: sfGuardAuth, action: index }

##################ApplyPlugin route################# 
apply:
 url:  /apply
 param: { module: sfApply, action: apply }
reset:
 url: /reset
 param: { module: sfApply, action: reset }
resetRequest:
 url: /reset-request
 param: { module: sfApply, action: resetRequest }
validate:
 url: /confirm/:validate
 param: { module: sfApply, action: confirm }
settings:
 url: /settings
 param: { module: sfApply, action: settings }
sf_guard_password_reset:
 url: /reset-request
 param: { module: sfApply, action: resetRequest }