# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: investmentapp, action: index }
####Route for message module for frontend
my_inbox:
 url: /inbox
 param: { module: messages, action: index}
####Route for my certificates
my_certificate:
 url: /issued/certificates
 param: {module: investmentcertificates, action: index }
# generic rules
# please, remove them by adding more specific rules
## Rules for EIA
project_detail:
 url: start/project/detail
 param: {module: projectDetail, action: new}
project_description:
 url: project/description
 param: {module: projectDescription, action: new}
project_surrounding_species:
 url: project/sorrounding/species
 param: {module: projectSorroundingSpecies, action: new}
project_social_economic:
 url: project/social/economic/environment
 param: {module: projectSocialEconomic, action: new}
project_impact_measures:
 url: project/impact/measures
 param: {module: projectImpactMeasures, action: new}
project_operation_phase:
 url: project/operation/phase
 param: {module: projectOperationPhase, action: new}
project_attachments:
 url: project/attachments
 param: {module: projectAttachment, action: new}
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
################### Application Security routing ################################
sf_guard_forgot_password:
 url:   /password_recover
 param: { module: sfGuardAuth, action: password }
sf_guard_recover_password:
 url: /recover
 param: {module: sfGuardForgotPassword, action: index}
sf_guard_users:
 url:   /users
 param: { module: sfGuardUser, action: index }
sf_guard_user_groups:
 url:   /groups
 param: { module: sfGuardGroup, action: index }
sf_guard_user_permissions:
 url:   /permissions
 param: { module: sfGuardPermission, action: index }
sf_guard_register:
 url:   /register
 param: { module: sfGuardAuth, action: index }

##################ApplyPlugin route################# 
apply:
 url:  /apply
 param: { module: sfApply, action: apply }
reset:
 url: /reset
 param: { module: sfApply, action: reset }
resetRequest:
 url: /reset-request
 param: { module: sfApply, action: resetRequest }
validate:
 url: /confirm/:validate
 param: { module: sfApply, action: confirm }
settings:
 url: /settings
 param: { module: sfApply, action: settings }
sf_guard_password_reset:
 url: /reset-request
 param: { module: sfApply, action: resetRequest }