# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        RDB - Investor Eportal System
    #description:  RDB Investor Eportal System 
    #keywords:     RDB, Investor Eportal System
    #language:     en
    #robots:       index, follow

<<<<<<< HEAD
  stylesheets:    [../bootstrap/css/bootstrap.min.css, ../bootstrap/css/bootstrap-responsive.min.css, ../font-awesome/css/font-awesome.css, style.css, style_responsive.css, style_grey.css, ../fancybox/source/jquery.fancybox.css, ../gritter/css/jquery.gritter.css, ../uniform/css/uniform.default.css, ../bootstrap-daterangepicker/daterangepicker.css, ../fullcalendar/fullcalendar/bootstrap-fullcalendar.css]
=======
  stylesheets:    [assets/bootstrap/css/bootstrap.min.css,assets/bootstrap/css/bootstrap-responsive.min.css,assets/font-awesome/css/font-awesome.css,assets/css/style.css,assets/css/style_responsive.css,assets/css/style_default.css,assets/fancybox/source/jquery.fancybox.css,assets/gritter/css/jquery.gritter.css,assets/uniform/css/uniform.default.css,assets/bootstrap-daterangepicker/daterangepicker.css,assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css,assets/jqvmap/jqvmap/jqvmap.css]

  javascripts:    [assets/js/jquery-1.8.2.min.js,assets/bootstrap/js/bootstrap.min.js,assets/js/jquery.blockui.js,assets/uniform/jquery.uniform.min.js,assets/fancybox/source/jquery.fancybox.pack.js,assets/js/app.js,http://code.highcharts.com/highcharts.js, http://code.highcharts.com/modules/exporting.js]
>>>>>>> 90b69d98ef9a6f53b8486de55a22d93c742d657f

  javascripts:    [ jquery-1.8.2.min.js, ../jQuery-slimScroll/jquery-ui-1.9.2.custom.min.js, ../jQuery-slimScroll/slimScroll.min.js, ../fullcalendar/fullcalendar/fullcalendar.min.js, ../bootstrap/js/bootstrap.min.js, jquery.blockui.js, jquery.cookie.js, jquery.peity.min.js, ../gritter/js/jquery.gritter.js, ../uniform/jquery.uniform.min.js, jquery.pulsate.min.js, ../bootstrap-daterangepicker/date.js, ../bootstrap-daterangepicker/daterangepicker.js, ../fancybox/source/jquery.fancybox.pack.js, app.js, ../flot/jquery.flot.js, ../flot/jquery.flot.resize.js ]
  has_layout:     true
  layout:         layout
