# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [assets/bootstrap/css/bootstrap.min.css,assets/bootstrap/css/bootstrap-responsive.min.css,assets/bootstrap/css/bootstrap-fileupload.css,assets/font-awesome/css/font-awesome.css,assets/css/style.css,assets/css/style_responsive.css,assets/css/website.css,assets/css/style_navygrey.css,assets/fancybox/source/jquery.fancybox.css,assets/gritter/css/jquery.gritter.css,assets/uniform/css/uniform.default.css,assets/bootstrap-daterangepicker/daterangepicker.css,assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css,assets/jqvmap/jqvmap/jqvmap.css,assets/chosen-bootstrap/chosen/chosen.css,assets/bootstrap-wysihtml5/bootstrap-wysihtml5.css,assets/bootstrap-datepicker/css/datepicker.css,assets/bootstrap-timepicker/compiled/timepicker.css,assets/bootstrap-colorpicker/css/colorpicker.css,assets/bootstrap-toggle-buttons/static/stylesheets/bootstrap-toggle-buttons.css,assets/data-tables/DT_bootstrap.css,assets/css/jquery.handsontable.full.css]

  javascripts:    [assets/js/jquery-1.8.2.min.js,assets/js/jquery.tinyscrollbar.min.js,assets/bootstrap/js/bootstrap.min.js,assets/bootstrap/js/bootstrap-fileupload.js,assets/js/jquery.blockui.js,assets/uniform/jquery.uniform.min.js,assets/fancybox/source/jquery.fancybox.pack.js,assets/js/app.js,highcharts/highcharts.js,highcharts/exporting.js,assets/chosen-bootstrap/chosen/chosen.jquery.min.js,assets/bootstrap-wysihtml5/wysihtml5-0.3.0.js,assets/bootstrap-wysihtml5/bootstrap-wysihtml5.js,assets/bootstrap-toggle-buttons/static/js/jquery.toggle.buttons.js,assets/bootstrap-datepicker/js/bootstrap-datepicker.js,assets/bootstrap-daterangepicker/date.js,assets/bootstrap-daterangepicker/daterangepicker.js,assets/bootstrap-timepicker/js/bootstrap-timepicker.js,assets/js/jquery.handsontable.full.js,tweets/jquery.timeago.js,tweets/jquery-tweets.js]

  has_layout:     true
  layout:         layout
