<?php
// This a cache config file for the sfTCPDFPlugin 
//
// auto-generated by sfTCPDFPluginConfigHandler
// date: 2013/04/17 22:33:03
return array (
  'default' => 
  array (
    'K_TCPDF_EXTERNAL_CONFIG' => true,
    'K_PATH_MAIN' => NULL,
    'K_PATH_URL' => NULL,
    'K_PATH_FONTS' => NULL,
    'K_PATH_CACHE' => NULL,
    'K_PATH_URL_CACHE' => NULL,
    'K_PATH_IMAGES' => NULL,
    'K_BLANK_IMAGE' => NULL,
    'PDF_PAGE_FORMAT' => 'A4',
    'PDF_PAGE_ORIENTATION' => 'P',
    'PDF_CREATOR' => 'TCPDF',
    'PDF_AUTHOR' => 'TCPDF',
    'PDF_HEADER_TITLE' => 'Rwanda Development Board',
    'PDF_HEADER_STRING' => 'E-portal System',
    'PDF_HEADER_LOGO' => 'logo.jpg',
    'PDF_HEADER_LOGO_WIDTH' => 30,
    'PDF_UNIT' => 'mm',
    'PDF_MARGIN_HEADER' => '5',
    'PDF_MARGIN_FOOTER' => '10',
    'PDF_MARGIN_TOP' => '27',
    'PDF_MARGIN_BOTTOM' => '25',
    'PDF_MARGIN_LEFT' => '15',
    'PDF_MARGIN_RIGHT' => '15',
    'PDF_FONT_NAME_MAIN' => 'helvetica',
    'PDF_FONT_SIZE_MAIN' => '10',
    'PDF_FONT_NAME_DATA' => 'helvetica',
    'PDF_FONT_SIZE_DATA' => '8',
    'PDF_FONT_MONOSPACED' => 'courier',
    'PDF_IMAGE_SCALE_RATIO' => '4',
    'HEAD_MAGNIFICATION' => '1.1',
    'K_CELL_HEIGHT_RATIO' => '1.25',
    'K_TITLE_MAGNIFICATION' => '1.3',
    'K_SMALL_RATIO' => '2/3',
    'K_THAI_TOPCHARS' => true,
    'K_TCPDF_CALLS_IN_HTML' => true,
  ),
  'my_config' => 
  array (
    'K_TCPDF_EXTERNAL_CONFIG' => true,
    'K_PATH_MAIN' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/',
    'K_PATH_URL' => 'http://dev.my-symfony-project/',
    'K_PATH_FONTS' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/fonts',
    'K_PATH_CACHE' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/cache',
    'K_PATH_URL_CACHE' => 'http://dev.my-symfony-project/cache',
    'K_PATH_IMAGES' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/images',
    'K_BLANK_IMAGE' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/images/_blank.png',
  ),
);
//
