<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/17 12:26:48
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'assignJob',
        1 => 'eiacert',
        2 => 'investmentcert',
        3 => 'investmentassign',
        4 => 'eiaassign',
      ),
    ),
  ),
);
