<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/02/11 17:05:16
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'assignJob',
  ),
  'index' => 
  array (
    'is_secure' => 'on',
    'credentials' => 'assignJob',
  ),
);
