<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/17 19:52:17
sfConfig::add(array(
  'mod_eireportresubmit_enabled' => true,
  'mod_eireportresubmit_view_class' => 'sfPHP',
));
