<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/11 15:30:56
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
