<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/13 12:16:37
sfConfig::add(array(
  'mod_projectsummary_enabled' => true,
  'mod_projectsummary_view_class' => 'sfPHP',
));
