<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/04/17 19:55:16
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'assignJob',
        1 => 'eiacert',
        2 => 'investmentcert',
        3 => 'investmentassign',
        4 => 'eiaassign',
      ),
    ),
  ),
);
