<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/17 20:36:02
sfConfig::add(array(
  'mod_eiacertificates_enabled' => true,
  'mod_eiacertificates_view_class' => 'sfPHP',
));
