<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/17 19:40:13
sfConfig::add(array(
  'mod_eiasitevisitreport_enabled' => true,
  'mod_eiasitevisitreport_view_class' => 'sfPHP',
));
