<?php

/**
 * sfKoreroChannelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfKoreroChannelTable extends PluginsfKoreroChannelTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfKoreroChannelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfKoreroChannel');
    }
}