<?php

/**
 * BusinessPlan form base class.
 *
 * @method BusinessPlan getObject() Returns the current form's model object
 *
 * @package    rdbeportal
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormGeneratedTemplate.php 29553 2010-05-20 14:33:00Z Kris.Wallsmith $
 */
abstract class BaseBusinessPlanForm extends BaseFormDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                              => new sfWidgetFormInputHidden(),
      'investment_id'                   => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('InvestmentApplication'), 'add_empty' => false)),
      'land_year1'                      => new sfWidgetFormInputText(),
      'land_year2'                      => new sfWidgetFormInputText(),
      'land_year3'                      => new sfWidgetFormInputText(),
      'land_year4'                      => new sfWidgetFormInputText(),
      'land_year5'                      => new sfWidgetFormInputText(),
      'construction_year1'              => new sfWidgetFormInputText(),
      'construction_year2'              => new sfWidgetFormInputText(),
      'construction_year3'              => new sfWidgetFormInputText(),
      'construction_year4'              => new sfWidgetFormInputText(),
      'construction_year5'              => new sfWidgetFormInputText(),
      'machinery_year1'                 => new sfWidgetFormInputText(),
      'machinery_year2'                 => new sfWidgetFormInputText(),
      'machinery_year3'                 => new sfWidgetFormInputText(),
      'machinery_year4'                 => new sfWidgetFormInputText(),
      'machinery_year5'                 => new sfWidgetFormInputText(),
      'furniture_year1'                 => new sfWidgetFormInputText(),
      'furniture_year2'                 => new sfWidgetFormInputText(),
      'furniture_year3'                 => new sfWidgetFormInputText(),
      'furniture_year4'                 => new sfWidgetFormInputText(),
      'furniture_year5'                 => new sfWidgetFormInputText(),
      'other_assets1'                   => new sfWidgetFormInputText(),
      'other_assets2'                   => new sfWidgetFormInputText(),
      'other_assets3'                   => new sfWidgetFormInputText(),
      'other_assets4'                   => new sfWidgetFormInputText(),
      'other_assets5'                   => new sfWidgetFormInputText(),
      'studies_year1'                   => new sfWidgetFormInputText(),
      'studies_year2'                   => new sfWidgetFormInputText(),
      'studies_year3'                   => new sfWidgetFormInputText(),
      'studies_year4'                   => new sfWidgetFormInputText(),
      'studies_year5'                   => new sfWidgetFormInputText(),
      'travel_expenses1'                => new sfWidgetFormInputText(),
      'travel_expenses2'                => new sfWidgetFormInputText(),
      'travel_expenses3'                => new sfWidgetFormInputText(),
      'travel_expenses4'                => new sfWidgetFormInputText(),
      'travel_expenses5'                => new sfWidgetFormInputText(),
      'starting_capital1'               => new sfWidgetFormInputText(),
      'starting_capital2'               => new sfWidgetFormInputText(),
      'starting_capital3'               => new sfWidgetFormInputText(),
      'starting_capital4'               => new sfWidgetFormInputText(),
      'starting_capital5'               => new sfWidgetFormInputText(),
      'licensing_expenses1'             => new sfWidgetFormInputText(),
      'licensing_expenses2'             => new sfWidgetFormInputText(),
      'licensing_expenses3'             => new sfWidgetFormInputText(),
      'licensing_expenses4'             => new sfWidgetFormInputText(),
      'licensing_expenses5'             => new sfWidgetFormInputText(),
      'rental_fees1'                    => new sfWidgetFormInputText(),
      'rental_fees2'                    => new sfWidgetFormInputText(),
      'rental_fees3'                    => new sfWidgetFormInputText(),
      'rental_fees4'                    => new sfWidgetFormInputText(),
      'rental_fees5'                    => new sfWidgetFormInputText(),
      'other_expeses1'                  => new sfWidgetFormInputText(),
      'other_expeses2'                  => new sfWidgetFormInputText(),
      'other_expeses3'                  => new sfWidgetFormInputText(),
      'other_expeses4'                  => new sfWidgetFormInputText(),
      'other_expeses5'                  => new sfWidgetFormInputText(),
      'equity_local'                    => new sfWidgetFormInputText(),
      'equity_foregin'                  => new sfWidgetFormInputText(),
      'bank_loan_local'                 => new sfWidgetFormInputText(),
      'bank_loan_foreign'               => new sfWidgetFormInputText(),
      'mother_company_loan_local'       => new sfWidgetFormInputText(),
      'mother_company_loan_foreign'     => new sfWidgetFormInputText(),
      'grant_local'                     => new sfWidgetFormInputText(),
      'grant_foreign'                   => new sfWidgetFormInputText(),
      'top_management_local1'           => new sfWidgetFormInputText(),
      'top_management_local2'           => new sfWidgetFormInputText(),
      'top_management_local3'           => new sfWidgetFormInputText(),
      'top_management_local4'           => new sfWidgetFormInputText(),
      'top_management_local5'           => new sfWidgetFormInputText(),
      'top_management_foreign1'         => new sfWidgetFormInputText(),
      'top_management_foreign2'         => new sfWidgetFormInputText(),
      'top_management_foreign3'         => new sfWidgetFormInputText(),
      'top_management_foreign4'         => new sfWidgetFormInputText(),
      'top_management_foreign5'         => new sfWidgetFormInputText(),
      'technical_professional_local1'   => new sfWidgetFormInputText(),
      'technical_professional_local2'   => new sfWidgetFormInputText(),
      'technical_professional_local3'   => new sfWidgetFormInputText(),
      'technical_professional_local4'   => new sfWidgetFormInputText(),
      'technical_professional_local5'   => new sfWidgetFormInputText(),
      'technical_professional_foreign1' => new sfWidgetFormInputText(),
      'technical_professional_foreign2' => new sfWidgetFormInputText(),
      'technical_professional_foreign3' => new sfWidgetFormInputText(),
      'technical_professional_foreign4' => new sfWidgetFormInputText(),
      'technical_professional_foreign5' => new sfWidgetFormInputText(),
      'skilled_labour_local1'           => new sfWidgetFormInputText(),
      'skilled_labour_local2'           => new sfWidgetFormInputText(),
      'skilled_labour_local3'           => new sfWidgetFormInputText(),
      'skilled_labour_local4'           => new sfWidgetFormInputText(),
      'skilled_labour_local5'           => new sfWidgetFormInputText(),
      'skilled_labour_foreign1'         => new sfWidgetFormInputText(),
      'skilled_labour_foreign2'         => new sfWidgetFormInputText(),
      'skilled_labour_foreign3'         => new sfWidgetFormInputText(),
      'skilled_labour_foreign4'         => new sfWidgetFormInputText(),
      'skilled_labour_foreign5'         => new sfWidgetFormInputText(),
      'other_jobs_local1'               => new sfWidgetFormInputText(),
      'other_jobs_local2'               => new sfWidgetFormInputText(),
      'other_jobs_local3'               => new sfWidgetFormInputText(),
      'other_jobs_local4'               => new sfWidgetFormInputText(),
      'other_jobs_local5'               => new sfWidgetFormInputText(),
      'other_jobs_foreign1'             => new sfWidgetFormInputText(),
      'other_jobs_foreign2'             => new sfWidgetFormInputText(),
      'other_jobs_foreign3'             => new sfWidgetFormInputText(),
      'other_jobs_foreign4'             => new sfWidgetFormInputText(),
      'other_jobs_foreign5'             => new sfWidgetFormInputText(),
      'sales_income1'                   => new sfWidgetFormInputText(),
      'sales_income2'                   => new sfWidgetFormInputText(),
      'sales_income3'                   => new sfWidgetFormInputText(),
      'sales_income4'                   => new sfWidgetFormInputText(),
      'sales_income5'                   => new sfWidgetFormInputText(),
      'total_cost_sales1'               => new sfWidgetFormInputText(),
      'total_cost_sales2'               => new sfWidgetFormInputText(),
      'total_cost_sales3'               => new sfWidgetFormInputText(),
      'total_cost_sales4'               => new sfWidgetFormInputText(),
      'total_cost_sales5'               => new sfWidgetFormInputText(),
      'gross_profit1'                   => new sfWidgetFormInputText(),
      'gross_profit2'                   => new sfWidgetFormInputText(),
      'gross_profit3'                   => new sfWidgetFormInputText(),
      'gross_profit4'                   => new sfWidgetFormInputText(),
      'gross_profit5'                   => new sfWidgetFormInputText(),
      'indirect_expenses1'              => new sfWidgetFormInputText(),
      'indirect_expenses2'              => new sfWidgetFormInputText(),
      'indirect_expenses3'              => new sfWidgetFormInputText(),
      'indirect_expenses4'              => new sfWidgetFormInputText(),
      'indirect_expenses5'              => new sfWidgetFormInputText(),
      'profit_before_tax1'              => new sfWidgetFormInputText(),
      'profit_before_tax2'              => new sfWidgetFormInputText(),
      'profit_before_tax3'              => new sfWidgetFormInputText(),
      'profit_before_tax4'              => new sfWidgetFormInputText(),
      'profit_before_tax5'              => new sfWidgetFormInputText(),
      'tax_expenses1'                   => new sfWidgetFormInputText(),
      'tax_expenses2'                   => new sfWidgetFormInputText(),
      'tax_expenses3'                   => new sfWidgetFormInputText(),
      'tax_expenses4'                   => new sfWidgetFormInputText(),
      'tax_expenses5'                   => new sfWidgetFormInputText(),
      'net_profit1'                     => new sfWidgetFormInputText(),
      'net_profit2'                     => new sfWidgetFormInputText(),
      'net_profit3'                     => new sfWidgetFormInputText(),
      'net_profit4'                     => new sfWidgetFormInputText(),
      'net_profit5'                     => new sfWidgetFormInputText(),
      'project_brief'                   => new sfWidgetFormTextarea(),
      'exemption_on_machinery'          => new sfWidgetFormInputText(),
      'exemption_raw_materials'         => new sfWidgetFormTextarea(),
      'land_ownership_document'         => new sfWidgetFormInputText(),
      'bill_of_quantiy'                 => new sfWidgetFormInputText(),
      'drawings'                        => new sfWidgetFormInputText(),
      'construction_permits'            => new sfWidgetFormInputText(),
      'investment_allowances'           => new sfWidgetFormInputText(),
      'additional_incentives'           => new sfWidgetFormTextarea(),
      'visa_work_permits'               => new sfWidgetFormTextarea(),
      'created_at'                      => new sfWidgetFormDateTime(),
      'updated_at'                      => new sfWidgetFormDateTime(),
      'created_by'                      => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Creator'), 'add_empty' => true)),
      'updated_by'                      => new sfWidgetFormTextarea(),
    ));

    $this->setValidators(array(
      'id'                              => new sfValidatorChoice(array('choices' => array($this->getObject()->get('id')), 'empty_value' => $this->getObject()->get('id'), 'required' => false)),
      'investment_id'                   => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('InvestmentApplication'))),
      'land_year1'                      => new sfValidatorInteger(array('required' => false)),
      'land_year2'                      => new sfValidatorInteger(array('required' => false)),
      'land_year3'                      => new sfValidatorInteger(array('required' => false)),
      'land_year4'                      => new sfValidatorInteger(array('required' => false)),
      'land_year5'                      => new sfValidatorInteger(array('required' => false)),
      'construction_year1'              => new sfValidatorInteger(array('required' => false)),
      'construction_year2'              => new sfValidatorInteger(array('required' => false)),
      'construction_year3'              => new sfValidatorInteger(array('required' => false)),
      'construction_year4'              => new sfValidatorInteger(array('required' => false)),
      'construction_year5'              => new sfValidatorInteger(array('required' => false)),
      'machinery_year1'                 => new sfValidatorInteger(array('required' => false)),
      'machinery_year2'                 => new sfValidatorInteger(array('required' => false)),
      'machinery_year3'                 => new sfValidatorInteger(array('required' => false)),
      'machinery_year4'                 => new sfValidatorInteger(array('required' => false)),
      'machinery_year5'                 => new sfValidatorInteger(array('required' => false)),
      'furniture_year1'                 => new sfValidatorInteger(array('required' => false)),
      'furniture_year2'                 => new sfValidatorInteger(array('required' => false)),
      'furniture_year3'                 => new sfValidatorInteger(array('required' => false)),
      'furniture_year4'                 => new sfValidatorInteger(array('required' => false)),
      'furniture_year5'                 => new sfValidatorInteger(array('required' => false)),
      'other_assets1'                   => new sfValidatorInteger(array('required' => false)),
      'other_assets2'                   => new sfValidatorInteger(array('required' => false)),
      'other_assets3'                   => new sfValidatorInteger(array('required' => false)),
      'other_assets4'                   => new sfValidatorInteger(array('required' => false)),
      'other_assets5'                   => new sfValidatorInteger(array('required' => false)),
      'studies_year1'                   => new sfValidatorInteger(array('required' => false)),
      'studies_year2'                   => new sfValidatorInteger(array('required' => false)),
      'studies_year3'                   => new sfValidatorInteger(array('required' => false)),
      'studies_year4'                   => new sfValidatorInteger(array('required' => false)),
      'studies_year5'                   => new sfValidatorInteger(array('required' => false)),
      'travel_expenses1'                => new sfValidatorInteger(array('required' => false)),
      'travel_expenses2'                => new sfValidatorInteger(array('required' => false)),
      'travel_expenses3'                => new sfValidatorInteger(array('required' => false)),
      'travel_expenses4'                => new sfValidatorInteger(array('required' => false)),
      'travel_expenses5'                => new sfValidatorInteger(array('required' => false)),
      'starting_capital1'               => new sfValidatorInteger(array('required' => false)),
      'starting_capital2'               => new sfValidatorInteger(array('required' => false)),
      'starting_capital3'               => new sfValidatorInteger(array('required' => false)),
      'starting_capital4'               => new sfValidatorInteger(array('required' => false)),
      'starting_capital5'               => new sfValidatorInteger(array('required' => false)),
      'licensing_expenses1'             => new sfValidatorInteger(array('required' => false)),
      'licensing_expenses2'             => new sfValidatorInteger(array('required' => false)),
      'licensing_expenses3'             => new sfValidatorInteger(array('required' => false)),
      'licensing_expenses4'             => new sfValidatorInteger(array('required' => false)),
      'licensing_expenses5'             => new sfValidatorInteger(array('required' => false)),
      'rental_fees1'                    => new sfValidatorInteger(array('required' => false)),
      'rental_fees2'                    => new sfValidatorInteger(array('required' => false)),
      'rental_fees3'                    => new sfValidatorInteger(array('required' => false)),
      'rental_fees4'                    => new sfValidatorInteger(array('required' => false)),
      'rental_fees5'                    => new sfValidatorInteger(array('required' => false)),
      'other_expeses1'                  => new sfValidatorInteger(array('required' => false)),
      'other_expeses2'                  => new sfValidatorInteger(array('required' => false)),
      'other_expeses3'                  => new sfValidatorInteger(array('required' => false)),
      'other_expeses4'                  => new sfValidatorInteger(array('required' => false)),
      'other_expeses5'                  => new sfValidatorInteger(array('required' => false)),
      'equity_local'                    => new sfValidatorInteger(array('required' => false)),
      'equity_foregin'                  => new sfValidatorInteger(array('required' => false)),
      'bank_loan_local'                 => new sfValidatorInteger(array('required' => false)),
      'bank_loan_foreign'               => new sfValidatorInteger(array('required' => false)),
      'mother_company_loan_local'       => new sfValidatorInteger(array('required' => false)),
      'mother_company_loan_foreign'     => new sfValidatorInteger(array('required' => false)),
      'grant_local'                     => new sfValidatorInteger(array('required' => false)),
      'grant_foreign'                   => new sfValidatorInteger(array('required' => false)),
      'top_management_local1'           => new sfValidatorInteger(array('required' => false)),
      'top_management_local2'           => new sfValidatorInteger(array('required' => false)),
      'top_management_local3'           => new sfValidatorInteger(array('required' => false)),
      'top_management_local4'           => new sfValidatorInteger(array('required' => false)),
      'top_management_local5'           => new sfValidatorInteger(array('required' => false)),
      'top_management_foreign1'         => new sfValidatorInteger(array('required' => false)),
      'top_management_foreign2'         => new sfValidatorInteger(array('required' => false)),
      'top_management_foreign3'         => new sfValidatorInteger(array('required' => false)),
      'top_management_foreign4'         => new sfValidatorInteger(array('required' => false)),
      'top_management_foreign5'         => new sfValidatorInteger(array('required' => false)),
      'technical_professional_local1'   => new sfValidatorInteger(array('required' => false)),
      'technical_professional_local2'   => new sfValidatorInteger(array('required' => false)),
      'technical_professional_local3'   => new sfValidatorInteger(array('required' => false)),
      'technical_professional_local4'   => new sfValidatorInteger(array('required' => false)),
      'technical_professional_local5'   => new sfValidatorInteger(array('required' => false)),
      'technical_professional_foreign1' => new sfValidatorInteger(array('required' => false)),
      'technical_professional_foreign2' => new sfValidatorInteger(array('required' => false)),
      'technical_professional_foreign3' => new sfValidatorInteger(array('required' => false)),
      'technical_professional_foreign4' => new sfValidatorInteger(array('required' => false)),
      'technical_professional_foreign5' => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_local1'           => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_local2'           => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_local3'           => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_local4'           => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_local5'           => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_foreign1'         => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_foreign2'         => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_foreign3'         => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_foreign4'         => new sfValidatorInteger(array('required' => false)),
      'skilled_labour_foreign5'         => new sfValidatorInteger(array('required' => false)),
      'other_jobs_local1'               => new sfValidatorInteger(array('required' => false)),
      'other_jobs_local2'               => new sfValidatorInteger(array('required' => false)),
      'other_jobs_local3'               => new sfValidatorInteger(array('required' => false)),
      'other_jobs_local4'               => new sfValidatorInteger(array('required' => false)),
      'other_jobs_local5'               => new sfValidatorInteger(array('required' => false)),
      'other_jobs_foreign1'             => new sfValidatorInteger(array('required' => false)),
      'other_jobs_foreign2'             => new sfValidatorInteger(array('required' => false)),
      'other_jobs_foreign3'             => new sfValidatorInteger(array('required' => false)),
      'other_jobs_foreign4'             => new sfValidatorInteger(array('required' => false)),
      'other_jobs_foreign5'             => new sfValidatorInteger(array('required' => false)),
      'sales_income1'                   => new sfValidatorInteger(array('required' => false)),
      'sales_income2'                   => new sfValidatorInteger(array('required' => false)),
      'sales_income3'                   => new sfValidatorInteger(array('required' => false)),
      'sales_income4'                   => new sfValidatorInteger(array('required' => false)),
      'sales_income5'                   => new sfValidatorInteger(array('required' => false)),
      'total_cost_sales1'               => new sfValidatorInteger(array('required' => false)),
      'total_cost_sales2'               => new sfValidatorInteger(array('required' => false)),
      'total_cost_sales3'               => new sfValidatorInteger(array('required' => false)),
      'total_cost_sales4'               => new sfValidatorInteger(array('required' => false)),
      'total_cost_sales5'               => new sfValidatorInteger(array('required' => false)),
      'gross_profit1'                   => new sfValidatorInteger(array('required' => false)),
      'gross_profit2'                   => new sfValidatorInteger(array('required' => false)),
      'gross_profit3'                   => new sfValidatorInteger(array('required' => false)),
      'gross_profit4'                   => new sfValidatorInteger(array('required' => false)),
      'gross_profit5'                   => new sfValidatorInteger(array('required' => false)),
      'indirect_expenses1'              => new sfValidatorInteger(array('required' => false)),
      'indirect_expenses2'              => new sfValidatorInteger(array('required' => false)),
      'indirect_expenses3'              => new sfValidatorInteger(array('required' => false)),
      'indirect_expenses4'              => new sfValidatorInteger(array('required' => false)),
      'indirect_expenses5'              => new sfValidatorInteger(array('required' => false)),
      'profit_before_tax1'              => new sfValidatorInteger(array('required' => false)),
      'profit_before_tax2'              => new sfValidatorInteger(array('required' => false)),
      'profit_before_tax3'              => new sfValidatorInteger(array('required' => false)),
      'profit_before_tax4'              => new sfValidatorInteger(array('required' => false)),
      'profit_before_tax5'              => new sfValidatorInteger(array('required' => false)),
      'tax_expenses1'                   => new sfValidatorInteger(array('required' => false)),
      'tax_expenses2'                   => new sfValidatorInteger(array('required' => false)),
      'tax_expenses3'                   => new sfValidatorInteger(array('required' => false)),
      'tax_expenses4'                   => new sfValidatorInteger(array('required' => false)),
      'tax_expenses5'                   => new sfValidatorInteger(array('required' => false)),
      'net_profit1'                     => new sfValidatorInteger(array('required' => false)),
      'net_profit2'                     => new sfValidatorInteger(array('required' => false)),
      'net_profit3'                     => new sfValidatorInteger(array('required' => false)),
      'net_profit4'                     => new sfValidatorInteger(array('required' => false)),
      'net_profit5'                     => new sfValidatorInteger(array('required' => false)),
      'project_brief'                   => new sfValidatorString(array('max_length' => 4000)),
      'exemption_on_machinery'          => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'exemption_raw_materials'         => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'land_ownership_document'         => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'bill_of_quantiy'                 => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'drawings'                        => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'construction_permits'            => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'investment_allowances'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'additional_incentives'           => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'visa_work_permits'               => new sfValidatorString(array('max_length' => 4000, 'required' => false)),
      'created_at'                      => new sfValidatorDateTime(),
      'updated_at'                      => new sfValidatorDateTime(),
      'created_by'                      => new sfValidatorDoctrineChoice(array('model' => $this->getRelatedModelName('Creator'), 'required' => false)),
      'updated_by'                      => new sfValidatorString(array('required' => false)),
    ));

    $this->validatorSchema->setPostValidator(
      new sfValidatorDoctrineUnique(array('model' => 'BusinessPlan', 'column' => array('investment_id')))
    );

    $this->widgetSchema->setNameFormat('business_plan[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'BusinessPlan';
  }

}
