<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/07 11:59:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rdbeportal',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
