<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/04/17 12:16:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rdbeportal',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
