<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/17 12:28:51
sfConfig::add(array(
  'mod_projectattachment_enabled' => true,
  'mod_projectattachment_view_class' => 'sfPHP',
));
