<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/17 12:28:25
sfConfig::add(array(
  'mod_projectoperationphase_enabled' => true,
  'mod_projectoperationphase_view_class' => 'sfPHP',
));
