<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/04/17 12:27:03
sfConfig::add(array(
  'mod_eiaprojectdeveloper_enabled' => true,
  'mod_eiaprojectdeveloper_view_class' => 'sfPHP',
));
