<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/02/08 11:25:12
$this->security = array (
  'settings' => 
  array (
    'is_secure' => true,
  ),
  'editemail' => 
  array (
    'is_secure' => true,
  ),
  'resetrequest' => 
  array (
    'is_secure' => false,
  ),
  'apply' => 
  array (
    'is_secure' => false,
  ),
  'reset' => 
  array (
    'is_secure' => false,
  ),
  'confirm' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
