### Author - Boniface Irunguh
### Email - Mwendia.bonface4@gmail.com
### Purpose - This file describes the Tables to be created for the RDB E-portal System. Uses Doctrine ORM
##################################### Database Tables  ##################################################
###Investment application table - Stores details of the investor
InvestmentApplication: 
 actAs: {Timestampable: ~}
 columns:
  business_name: {type: string(255), notnull: true}
  email_address: {type: string(255), notnull: true}
  phone_number: {type: string(255), notnull: false}
  application_letter: {type: string(255), notnull: true}
  executive_summary: {type: string(400), notnull: true}
  promoter_profile: {type: string(400), notnull: true}
  project_backgroud: {type: string(400), notnull: true}
  market_study: {type: string(400), notnull: true}
  investment_plan: {type: string(400), notnull: true}
  equity_financing: {type: string(400), notnull: true}
  income_expenditure: {type: string(400), notnull: true}
  balance_sheet: {type: string(400), notnull: true}
  cash_flow: {type: string(400), notnull: true}
  payback_period: {type: string(400), notnull: true}
  loan_amortazation: {type: string(400), notnull: true}
  username_logged: {type: string(255), notnull: true}
