generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TaskAssignment
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          task_assignment
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  {user_assigned: [label: User Assigned, help: The User who is responsible for processing this record]}
      list:    ~
      filter:  {display: [user_assigned]}
      form:    ~
      edit:    {title: Edit Job Assigned To %%investmentapp_id%%}
      new:     {title: Assign A New Task To a Data Admin}
